export const pagingData = [
  {
    year: 1990,
    "Onshore wind": 1,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 11,
    "Large scale Hydro": 437,
    "Plant biomass": 0,
    "Animal biomass": 0,
    "Landfill gas": 46,
    "Sewage gas": 104,
  },
  {
    year: 1991,
    "Onshore wind": 1,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 12,
    "Large scale Hydro": 385,
    "Plant biomass": 0,
    "Animal biomass": 0,
    "Landfill gas": 68,
    "Sewage gas": 108,
  },
  {
    year: 1992,
    "Onshore wind": 3,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 13,
    "Large scale Hydro": 454,
    "Plant biomass": 0,
    "Animal biomass": 17,
    "Landfill gas": 124,
    "Sewage gas": 108,
  },
  {
    year: 1993,
    "Onshore wind": 19,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 14,
    "Large scale Hydro": 356,
    "Plant biomass": 0,
    "Animal biomass": 52,
    "Landfill gas": 147,
    "Sewage gas": 124,
  },
  {
    year: 1994,
    "Onshore wind": 30,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 14,
    "Large scale Hydro": 424,
    "Plant biomass": 0,
    "Animal biomass": 71,
    "Landfill gas": 170,
    "Sewage gas": 118,
  },
  {
    year: 1995,
    "Onshore wind": 34,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 14,
    "Large scale Hydro": 402,
    "Plant biomass": 0,
    "Animal biomass": 71,
    "Landfill gas": 184,
    "Sewage gas": 135,
  },
  {
    year: 1996,
    "Onshore wind": 42,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 10,
    "Large scale Hydro": 282,
    "Plant biomass": 0,
    "Animal biomass": 67,
    "Landfill gas": 232,
    "Sewage gas": 135,
  },
  {
    year: 1997,
    "Onshore wind": 57,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 14,
    "Large scale Hydro": 344,
    "Plant biomass": 0,
    "Animal biomass": 68,
    "Landfill gas": 301,
    "Sewage gas": 134,
  },
  {
    year: 1998,
    "Onshore wind": 75,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 18,
    "Large scale Hydro": 422,
    "Plant biomass": 0,
    "Animal biomass": 76,
    "Landfill gas": 389,
    "Sewage gas": 126,
  },
  {
    year: 1999,
    "Onshore wind": 73,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 18,
    "Large scale Hydro": 441,
    "Plant biomass": 0,
    "Animal biomass": 157,
    "Landfill gas": 558,
    "Sewage gas": 135,
  },
  {
    year: 2000,
    "Onshore wind": 81,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 18,
    "Large scale Hydro": 419,
    "Plant biomass": 11,
    "Animal biomass": 183,
    "Landfill gas": 718,
    "Sewage gas": 120,
  },
  {
    year: 2001,
    "Onshore wind": 83,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 18,
    "Large scale Hydro": 331,
    "Plant biomass": 81,
    "Animal biomass": 205,
    "Landfill gas": 822,
    "Sewage gas": 119,
  },
  {
    year: 2002,
    "Onshore wind": 108,
    "Offshore wind": 0,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 18,
    "Large scale Hydro": 394,
    "Plant biomass": 92,
    "Animal biomass": 184,
    "Landfill gas": 879,
    "Sewage gas": 121,
  },
  {
    year: 2003,
    "Onshore wind": 110,
    "Offshore wind": 1,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 13,
    "Large scale Hydro": 257,
    "Plant biomass": 137,
    "Animal biomass": 169,
    "Landfill gas": 1075,
    "Sewage gas": 129,
  },
  {
    year: 2004,
    "Onshore wind": 149,
    "Offshore wind": 17,
    "Marine energy": 0,
    "Solar photovoltaics": 0,
    "Small scale Hydro": 24,
    "Large scale Hydro": 392,
    "Plant biomass": 123,
    "Animal biomass": 179,
    "Landfill gas": 1313,
    "Sewage gas": 144,
  },
  {
    year: 2005,
    "Onshore wind": 215,
    "Offshore wind": 35,
    "Marine energy": 0,
    "Solar photovoltaics": 1,
    "Small scale Hydro": 38,
    "Large scale Hydro": 385,
    "Plant biomass": 129,
    "Animal biomass": 159,
    "Landfill gas": 1407,
    "Sewage gas": 153,
  },
  {
    year: 2006,
    "Onshore wind": 307,
    "Offshore wind": 56,
    "Marine energy": 0,
    "Solar photovoltaics": 1,
    "Small scale Hydro": 41,
    "Large scale Hydro": 354,
    "Plant biomass": 123,
    "Animal biomass": 145,
    "Landfill gas": 1451,
    "Sewage gas": 146,
  },
  {
    year: 2007,
    "Onshore wind": 386,
    "Offshore wind": 67,
    "Marine energy": 0,
    "Solar photovoltaics": 1,
    "Small scale Hydro": 45,
    "Large scale Hydro": 392,
    "Plant biomass": 138,
    "Animal biomass": 218,
    "Landfill gas": 1534,
    "Sewage gas": 162,
  },
  {
    year: 2008,
    "Onshore wind": 498,
    "Offshore wind": 115,
    "Marine energy": 0,
    "Solar photovoltaics": 1,
    "Small scale Hydro": 47,
    "Large scale Hydro": 396,
    "Plant biomass": 242,
    "Animal biomass": 260,
    "Landfill gas": 1540,
    "Sewage gas": 180,
  },
  {
    year: 2009,
    "Onshore wind": 647,
    "Offshore wind": 151,
    "Marine energy": 0,
    "Solar photovoltaics": 2,
    "Small scale Hydro": 49,
    "Large scale Hydro": 401,
    "Plant biomass": 387,
    "Animal biomass": 232,
    "Landfill gas": 1613,
    "Sewage gas": 198,
  },
  {
    year: 2010,
    "Onshore wind": 621,
    "Offshore wind": 263,
    "Marine energy": 0,
    "Solar photovoltaics": 3,
    "Small scale Hydro": 43,
    "Large scale Hydro": 266,
    "Plant biomass": 461,
    "Animal biomass": 239,
    "Landfill gas": 1711,
    "Sewage gas": 237,
  },
  {
    year: 2011,
    "Onshore wind": 930,
    "Offshore wind": 443,
    "Marine energy": 0,
    "Solar photovoltaics": 21,
    "Small scale Hydro": 61,
    "Large scale Hydro": 429,
    "Plant biomass": 554,
    "Animal biomass": 224,
    "Landfill gas": 1744,
    "Sewage gas": 254,
  },
  {
    year: 2012,
    "Onshore wind": 1053,
    "Offshore wind": 654,
    "Marine energy": 0,
    "Solar photovoltaics": 116,
    "Small scale Hydro": 58,
    "Large scale Hydro": 398,
    "Plant biomass": 1062,
    "Animal biomass": 225,
    "Landfill gas": 1708,
    "Sewage gas": 242,
  },
  {
    year: 2013,
    "Onshore wind": 1455,
    "Offshore wind": 986,
    "Marine energy": 0,
    "Solar photovoltaics": 173,
    "Small scale Hydro": 58,
    "Large scale Hydro": 346,
    "Plant biomass": 2008,
    "Animal biomass": 226,
    "Landfill gas": 1697,
    "Sewage gas": 251,
  },
  {
    year: 2014,
    "Onshore wind": 1595,
    "Offshore wind": 1153,
    "Marine energy": 0,
    "Solar photovoltaics": 349,
    "Small scale Hydro": 72,
    "Large scale Hydro": 435,
    "Plant biomass": 2913,
    "Animal biomass": 225,
    "Landfill gas": 1651,
    "Sewage gas": 276,
  },
  {
    year: 2015,
    "Onshore wind": 1965,
    "Offshore wind": 1498,
    "Marine energy": 0,
    "Solar photovoltaics": 648,
    "Small scale Hydro": 85,
    "Large scale Hydro": 457,
    "Plant biomass": 3850,
    "Animal biomass": 235,
    "Landfill gas": 1598,
    "Sewage gas": 293,
  },
  {
    year: 2016,
    "Onshore wind": 1785,
    "Offshore wind": 1411,
    "Marine energy": 0,
    "Solar photovoltaics": 894,
    "Small scale Hydro": 87,
    "Large scale Hydro": 374,
    "Plant biomass": 3855,
    "Animal biomass": 230,
    "Landfill gas": 1542,
    "Sewage gas": 312,
  },
  {
    year: 2017,
    "Onshore wind": 2470,
    "Offshore wind": 1798,
    "Marine energy": 0,
    "Solar photovoltaics": 985,
    "Small scale Hydro": 112,
    "Large scale Hydro": 394,
    "Plant biomass": 4206,
    "Animal biomass": 226,
    "Landfill gas": 1405,
    "Sewage gas": 317,
  },
  {
    year: 2018,
    "Onshore wind": 2612,
    "Offshore wind": 2281,
    "Marine energy": 1,
    "Solar photovoltaics": 1089,
    "Small scale Hydro": 111,
    "Large scale Hydro": 357,
    "Plant biomass": 4898,
    "Animal biomass": 219,
    "Landfill gas": 1284,
    "Sewage gas": 325,
  },
  {
    year: 2019,
    "Onshore wind": 2739,
    "Offshore wind": 2749,
    "Marine energy": 1,
    "Solar photovoltaics": 1068,
    "Small scale Hydro": 120,
    "Large scale Hydro": 390,
    "Plant biomass": 5400,
    "Animal biomass": 243,
    "Landfill gas": 866,
    "Sewage gas": 233,
  },
  {
    year: 2020,
    "Onshore wind": 3004,
    "Offshore wind": 3498,
    "Marine energy": 1,
    "Solar photovoltaics": 1109,
    "Small scale Hydro": 134,
    "Large scale Hydro": 456,
    "Plant biomass": 5637,
    "Animal biomass": 241,
    "Landfill gas": 835,
    "Sewage gas": 237,
  },
  {
    year: 2021,
    "Onshore wind": 2507,
    "Offshore wind": 3053,
    "Marine energy": 0,
    "Solar photovoltaics": 1044,
    "Small scale Hydro": 119,
    "Large scale Hydro": 353,
    "Plant biomass": 5990,
    "Animal biomass": 240,
    "Landfill gas": 791,
    "Sewage gas": 233,
  },
];