export const employeeDetails: object[] = [
    {
        "FirstName": "David",
        "LastName": "Jones",
        "Email": "david.jones@company.com",
        "Phone": "+1-334-902-3993",
        "Department": "Marketing",
        "Role": "Manager",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1449889901523),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10000.jpg",
        "Skills": [
            "Communication",
            "Leadership",
            "SEO"
        ],
        "PerformanceScore": 86,
        "LastReviewDate": new Date(1723950701523),
        "ManagerId": "EMP-191",
        "LinkedIn": "linkedin.com/in/david0",
        "Experience": 9.6,
        "EmployeeID": 10000
    },
    {
        "FirstName": "Emma",
        "LastName": "Brown",
        "Email": "emma.brown@company.com",
        "Phone": "+1-742-204-5269",
        "Department": "Sales",
        "Role": "QA Analyst",
        "Location": "Chicago, USA",
        "HireDate": new Date(1521169901523),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10001.jpg",
        "Skills": [
            "Node.js",
            "Python",
            "React"
        ],
        "PerformanceScore": 82,
        "LastReviewDate": new Date(1744168301523),
        "ManagerId": "EMP-180",
        "LinkedIn": "linkedin.com/in/emma1",
        "Experience": 7.4,
        "EmployeeID": 10001
    },
    {
        "FirstName": "Emma",
        "LastName": "Hernandez",
        "Email": "emma.hernandez@company.com",
        "Phone": "+1-246-599-6556",
        "Department": "Marketing",
        "Role": "QA Analyst",
        "Location": "New York, USA",
        "HireDate": new Date(1597720301523),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10002.jpg",
        "Skills": [
            "React",
            "Leadership",
            "SAP"
        ],
        "PerformanceScore": 95,
        "LastReviewDate": new Date(1745809901523),
        "ManagerId": "EMP-104",
        "LinkedIn": "linkedin.com/in/emma2",
        "Experience": 4.9,
        "EmployeeID": 10002
    },
    {
        "FirstName": "Emily",
        "LastName": "Brown",
        "Email": "emily.brown@company.com",
        "Phone": "+1-179-707-9780",
        "Department": "Finance",
        "Role": "Devops Engineer",
        "Location": "Chicago, USA",
        "HireDate": new Date(1524453101523),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10003.jpg",
        "Skills": [
            "SEO",
            "Java",
            "Leadership"
        ],
        "PerformanceScore": 91,
        "LastReviewDate": new Date(1734318701523),
        "ManagerId": "EMP-145",
        "LinkedIn": "linkedin.com/in/emily3",
        "Experience": 7.3,
        "EmployeeID": 10003
    },
    {
        "FirstName": "Michael",
        "LastName": "Martinez",
        "Email": "michael.martinez@company.com",
        "Phone": "+1-512-334-6660",
        "Department": "Sales",
        "Role": "Developer",
        "Location": "Chicago, USA",
        "HireDate": new Date(1439694701523),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10004.jpg",
        "Skills": [
            "React",
            "Node.js",
            "Communication"
        ],
        "PerformanceScore": 52,
        "LastReviewDate": new Date(1727147501523),
        "ManagerId": "EMP-146",
        "LinkedIn": "linkedin.com/in/michael4",
        "Experience": 9.9,
        "EmployeeID": 10004
    },
    {
        "FirstName": "Emma",
        "LastName": "Garcia",
        "Email": "emma.garcia@company.com",
        "Phone": "+1-968-567-3686",
        "Department": "Finance",
        "Role": "Manager",
        "Location": "Seattle, USA",
        "HireDate": new Date(1460344301523),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10005.jpg",
        "Skills": [
            "Node.js",
            "Leadership",
            "SEO"
        ],
        "PerformanceScore": 70,
        "LastReviewDate": new Date(1743736301523),
        "ManagerId": "EMP-150",
        "LinkedIn": "linkedin.com/in/emma5",
        "Experience": 9.3,
        "EmployeeID": 10005
    },
    {
        "FirstName": "James",
        "LastName": "Williams",
        "Email": "james.williams@company.com",
        "Phone": "+1-745-257-1661",
        "Department": "Sales",
        "Role": "Recruiter",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1693192301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10006.jpg",
        "Skills": [
            "Node.js",
            "React",
            "Java"
        ],
        "PerformanceScore": 78,
        "LastReviewDate": new Date(1739934701524),
        "ManagerId": "EMP-127",
        "LinkedIn": "linkedin.com/in/james6",
        "Experience": 1.9,
        "EmployeeID": 10006
    },
    {
        "FirstName": "Sarah",
        "LastName": "Smith",
        "Email": "sarah.smith@company.com",
        "Phone": "+1-384-933-1262",
        "Department": "Sales",
        "Role": "Accountant",
        "Location": "New York, USA",
        "HireDate": new Date(1490411501524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10007.jpg",
        "Skills": [
            "Python",
            "React",
            "Java"
        ],
        "PerformanceScore": 88,
        "LastReviewDate": new Date(1736219501524),
        "ManagerId": "EMP-129",
        "LinkedIn": "linkedin.com/in/sarah7",
        "Experience": 8.3,
        "EmployeeID": 10007
    },
    {
        "FirstName": "Michael",
        "LastName": "Johnson",
        "Email": "michael.johnson@company.com",
        "Phone": "+1-377-432-5865",
        "Department": "HR",
        "Role": "Analyst",
        "Location": "New York, USA",
        "HireDate": new Date(1672801901524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10008.jpg",
        "Skills": [
            "Java",
            "Leadership",
            "SAP"
        ],
        "PerformanceScore": 81,
        "LastReviewDate": new Date(1747451501524),
        "ManagerId": "EMP-195",
        "LinkedIn": "linkedin.com/in/michael8",
        "Experience": 2.6,
        "EmployeeID": 10008
    },
    {
        "FirstName": "James",
        "LastName": "Hernandez",
        "Email": "james.hernandez@company.com",
        "Phone": "+1-592-818-5181",
        "Department": "Sales",
        "Role": "Devops Engineer",
        "Location": "Chicago, USA",
        "HireDate": new Date(1510974701524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10009.jpg",
        "Skills": [
            "SEO",
            "Leadership",
            "SAP"
        ],
        "PerformanceScore": 54,
        "LastReviewDate": new Date(1733195501524),
        "ManagerId": "EMP-115",
        "LinkedIn": "linkedin.com/in/james9",
        "Experience": 7.7,
        "EmployeeID": 10009
    },
    {
        "FirstName": "Michael",
        "LastName": "Martinez",
        "Email": "michael.martinez@company.com",
        "Phone": "+1-419-593-8362",
        "Department": "HR",
        "Role": "Analyst",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1700277101524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10010.jpg",
        "Skills": [
            "Python",
            "SAP",
            "SEO"
        ],
        "PerformanceScore": 100,
        "LastReviewDate": new Date(1731208301524),
        "ManagerId": "EMP-186",
        "LinkedIn": "linkedin.com/in/michael10",
        "Experience": 1.7,
        "EmployeeID": 10010
    },
    {
        "FirstName": "Sarah",
        "LastName": "Johnson",
        "Email": "sarah.johnson@company.com",
        "Phone": "+1-405-127-8416",
        "Department": "Marketing",
        "Role": "Manager",
        "Location": "Seattle, USA",
        "HireDate": new Date(1600744301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10011.jpg",
        "Skills": [
            "Node.js",
            "React",
            "Communication"
        ],
        "PerformanceScore": 65,
        "LastReviewDate": new Date(1727147501524),
        "ManagerId": "EMP-104",
        "LinkedIn": "linkedin.com/in/sarah11",
        "Experience": 4.8,
        "EmployeeID": 10011
    },
    {
        "FirstName": "David",
        "LastName": "Smith",
        "Email": "david.smith@company.com",
        "Phone": "+1-973-391-1604",
        "Department": "Engineering",
        "Role": "Accountant",
        "Location": "Austin, USA",
        "HireDate": new Date(1534734701524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10012.jpg",
        "Skills": [
            "Python",
            "React",
            "Java"
        ],
        "PerformanceScore": 99,
        "LastReviewDate": new Date(1746414701524),
        "ManagerId": "EMP-104",
        "LinkedIn": "linkedin.com/in/david12",
        "Experience": 6.9,
        "EmployeeID": 10012
    },
    {
        "FirstName": "Olivia",
        "LastName": "Miller",
        "Email": "olivia.miller@company.com",
        "Phone": "+1-493-661-8497",
        "Department": "Marketing",
        "Role": "Accountant",
        "Location": "Chicago, USA",
        "HireDate": new Date(1611976301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10013.jpg",
        "Skills": [
            "Communication",
            "Leadership",
            "Node.js"
        ],
        "PerformanceScore": 76,
        "LastReviewDate": new Date(1727147501524),
        "ManagerId": "EMP-183",
        "LinkedIn": "linkedin.com/in/olivia13",
        "Experience": 4.5,
        "EmployeeID": 10013
    },
    {
        "FirstName": "Michael",
        "LastName": "Johnson",
        "Email": "michael.johnson@company.com",
        "Phone": "+1-436-336-9207",
        "Department": "Support",
        "Role": "Designer",
        "Location": "Seattle, USA",
        "HireDate": new Date(1504235501524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10014.jpg",
        "Skills": [
            "Java",
            "Communication",
            "Python"
        ],
        "PerformanceScore": 81,
        "LastReviewDate": new Date(1745809901524),
        "ManagerId": "EMP-149",
        "LinkedIn": "linkedin.com/in/michael14",
        "Experience": 7.9,
        "EmployeeID": 10014
    },
    {
        "FirstName": "Emma",
        "LastName": "Miller",
        "Email": "emma.miller@company.com",
        "Phone": "+1-989-695-6223",
        "Department": "Marketing",
        "Role": "Manager",
        "Location": "Seattle, USA",
        "HireDate": new Date(1556939501524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10015.jpg",
        "Skills": [
            "React",
            "Python",
            "Communication"
        ],
        "PerformanceScore": 76,
        "LastReviewDate": new Date(1724296301524),
        "ManagerId": "EMP-176",
        "LinkedIn": "linkedin.com/in/emma15",
        "Experience": 6.2,
        "EmployeeID": 10015
    },
    {
        "FirstName": "Sarah",
        "LastName": "Jones",
        "Email": "sarah.jones@company.com",
        "Phone": "+1-367-999-3819",
        "Department": "HR",
        "Role": "QA Analyst",
        "Location": "Seattle, USA",
        "HireDate": new Date(1445915501524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10016.jpg",
        "Skills": [
            "SAP",
            "SEO",
            "Node.js"
        ],
        "PerformanceScore": 67,
        "LastReviewDate": new Date(1739589101524),
        "ManagerId": "EMP-196",
        "LinkedIn": "linkedin.com/in/sarah16",
        "Experience": 9.7,
        "EmployeeID": 10016
    },
    {
        "FirstName": "Emma",
        "LastName": "Garcia",
        "Email": "emma.garcia@company.com",
        "Phone": "+1-203-825-5286",
        "Department": "Engineering",
        "Role": "Developer",
        "Location": "Austin, USA",
        "HireDate": new Date(1545880301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10017.jpg",
        "Skills": [
            "SEO",
            "Java",
            "Node.js"
        ],
        "PerformanceScore": 85,
        "LastReviewDate": new Date(1726110701524),
        "ManagerId": "EMP-173",
        "LinkedIn": "linkedin.com/in/emma17",
        "Experience": 6.6,
        "EmployeeID": 10017
    },
    {
        "FirstName": "David",
        "LastName": "Williams",
        "Email": "david.williams@company.com",
        "Phone": "+1-955-987-4164",
        "Department": "HR",
        "Role": "Manager",
        "Location": "Austin, USA",
        "HireDate": new Date(1589425901524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10018.jpg",
        "Skills": [
            "Java",
            "React",
            "SAP"
        ],
        "PerformanceScore": 84,
        "LastReviewDate": new Date(1745723501524),
        "ManagerId": "EMP-131",
        "LinkedIn": "linkedin.com/in/david18",
        "Experience": 5.2,
        "EmployeeID": 10018
    },
    {
        "FirstName": "James",
        "LastName": "Hernandez",
        "Email": "james.hernandez@company.com",
        "Phone": "+1-285-305-3720",
        "Department": "HR",
        "Role": "Developer",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1457665901524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10019.jpg",
        "Skills": [
            "Python",
            "SAP",
            "SEO"
        ],
        "PerformanceScore": 78,
        "LastReviewDate": new Date(1728270701524),
        "ManagerId": "EMP-148",
        "LinkedIn": "linkedin.com/in/james19",
        "Experience": 9.4,
        "EmployeeID": 10019
    },
    {
        "FirstName": "Emily",
        "LastName": "Brown",
        "Email": "emily.brown@company.com",
        "Phone": "+1-689-484-1896",
        "Department": "HR",
        "Role": "Manager",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1484104301524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10020.jpg",
        "Skills": [
            "Python",
            "React",
            "SEO"
        ],
        "PerformanceScore": 96,
        "LastReviewDate": new Date(1745118701524),
        "ManagerId": "EMP-115",
        "LinkedIn": "linkedin.com/in/emily20",
        "Experience": 8.5,
        "EmployeeID": 10020
    },
    {
        "FirstName": "Sarah",
        "LastName": "Brown",
        "Email": "sarah.brown@company.com",
        "Phone": "+1-299-997-1313",
        "Department": "Finance",
        "Role": "Devops Engineer",
        "Location": "Seattle, USA",
        "HireDate": new Date(1638587501524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10021.jpg",
        "Skills": [
            "Leadership",
            "SEO",
            "SAP"
        ],
        "PerformanceScore": 82,
        "LastReviewDate": new Date(1743563501524),
        "ManagerId": "EMP-156",
        "LinkedIn": "linkedin.com/in/sarah21",
        "Experience": 3.6,
        "EmployeeID": 10021
    },
    {
        "FirstName": "Emily",
        "LastName": "Williams",
        "Email": "emily.williams@company.com",
        "Phone": "+1-237-229-7821",
        "Department": "Sales",
        "Role": "Designer",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1535339501524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10022.jpg",
        "Skills": [
            "SEO",
            "Java",
            "Node.js"
        ],
        "PerformanceScore": 52,
        "LastReviewDate": new Date(1722049901524),
        "ManagerId": "EMP-103",
        "LinkedIn": "linkedin.com/in/emily22",
        "Experience": 6.9,
        "EmployeeID": 10022
    },
    {
        "FirstName": "Olivia",
        "LastName": "Brown",
        "Email": "olivia.brown@company.com",
        "Phone": "+1-739-721-3563",
        "Department": "Marketing",
        "Role": "Analyst",
        "Location": "New York, USA",
        "HireDate": new Date(1500865901524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10023.jpg",
        "Skills": [
            "React",
            "Communication",
            "Node.js"
        ],
        "PerformanceScore": 58,
        "LastReviewDate": new Date(1745723501524),
        "ManagerId": "EMP-162",
        "LinkedIn": "linkedin.com/in/olivia23",
        "Experience": 8.0,
        "EmployeeID": 10023
    },
    {
        "FirstName": "Sarah",
        "LastName": "Miller",
        "Email": "sarah.miller@company.com",
        "Phone": "+1-882-889-4455",
        "Department": "Sales",
        "Role": "QA Analyst",
        "Location": "Austin, USA",
        "HireDate": new Date(1615518701524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10024.jpg",
        "Skills": [
            "Leadership",
            "Java",
            "Communication"
        ],
        "PerformanceScore": 99,
        "LastReviewDate": new Date(1750129901524),
        "ManagerId": "EMP-112",
        "LinkedIn": "linkedin.com/in/sarah24",
        "Experience": 4.4,
        "EmployeeID": 10024
    },
    {
        "FirstName": "Laura",
        "LastName": "Jones",
        "Email": "laura.jones@company.com",
        "Phone": "+1-211-940-2554",
        "Department": "Sales",
        "Role": "Developer",
        "Location": "Seattle, USA",
        "HireDate": new Date(1649041901524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10025.jpg",
        "Skills": [
            "Leadership",
            "Java",
            "SAP"
        ],
        "PerformanceScore": 79,
        "LastReviewDate": new Date(1734923501524),
        "ManagerId": "EMP-140",
        "LinkedIn": "linkedin.com/in/laura25",
        "Experience": 3.3,
        "EmployeeID": 10025
    },
    {
        "FirstName": "John",
        "LastName": "Jones",
        "Email": "john.jones@company.com",
        "Phone": "+1-397-225-7379",
        "Department": "Finance",
        "Role": "Devops Engineer",
        "Location": "Chicago, USA",
        "HireDate": new Date(1642734701524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10026.jpg",
        "Skills": [
            "Java",
            "Python",
            "Node.js"
        ],
        "PerformanceScore": 73,
        "LastReviewDate": new Date(1727838701524),
        "ManagerId": "EMP-107",
        "LinkedIn": "linkedin.com/in/john26",
        "Experience": 3.5,
        "EmployeeID": 10026
    },
    {
        "FirstName": "Sarah",
        "LastName": "Smith",
        "Email": "sarah.smith@company.com",
        "Phone": "+1-795-224-9132",
        "Department": "Support",
        "Role": "Accountant",
        "Location": "Chicago, USA",
        "HireDate": new Date(1470021101524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10027.jpg",
        "Skills": [
            "Node.js",
            "Leadership",
            "Java"
        ],
        "PerformanceScore": 75,
        "LastReviewDate": new Date(1748833901524),
        "ManagerId": "EMP-113",
        "LinkedIn": "linkedin.com/in/sarah27",
        "Experience": 9.0,
        "EmployeeID": 10027
    },
    {
        "FirstName": "James",
        "LastName": "Jones",
        "Email": "james.jones@company.com",
        "Phone": "+1-579-691-2238",
        "Department": "Sales",
        "Role": "Designer",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1604718701524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10028.jpg",
        "Skills": [
            "SEO",
            "React",
            "SAP"
        ],
        "PerformanceScore": 92,
        "LastReviewDate": new Date(1732763501524),
        "ManagerId": "EMP-199",
        "LinkedIn": "linkedin.com/in/james28",
        "Experience": 4.7,
        "EmployeeID": 10028
    },
    {
        "FirstName": "John",
        "LastName": "Miller",
        "Email": "john.miller@company.com",
        "Phone": "+1-387-893-8441",
        "Department": "Sales",
        "Role": "Analyst",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1535339501524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10029.jpg",
        "Skills": [
            "Java",
            "SAP",
            "Node.js"
        ],
        "PerformanceScore": 91,
        "LastReviewDate": new Date(1742613101524),
        "ManagerId": "EMP-138",
        "LinkedIn": "linkedin.com/in/john29",
        "Experience": 6.9,
        "EmployeeID": 10029
    },
    {
        "FirstName": "James",
        "LastName": "Jones",
        "Email": "james.jones@company.com",
        "Phone": "+1-598-886-1102",
        "Department": "Engineering",
        "Role": "Analyst",
        "Location": "Chicago, USA",
        "HireDate": new Date(1654744301524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10030.jpg",
        "Skills": [
            "React",
            "Python",
            "SAP"
        ],
        "PerformanceScore": 59,
        "LastReviewDate": new Date(1723864301524),
        "ManagerId": "EMP-149",
        "LinkedIn": "linkedin.com/in/james30",
        "Experience": 3.1,
        "EmployeeID": 10030
    },
    {
        "FirstName": "Laura",
        "LastName": "Miller",
        "Email": "laura.miller@company.com",
        "Phone": "+1-467-654-6955",
        "Department": "Marketing",
        "Role": "Accountant",
        "Location": "New York, USA",
        "HireDate": new Date(1484536301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10031.jpg",
        "Skills": [
            "SAP",
            "SEO",
            "Node.js"
        ],
        "PerformanceScore": 81,
        "LastReviewDate": new Date(1743736301524),
        "ManagerId": "EMP-107",
        "LinkedIn": "linkedin.com/in/laura31",
        "Experience": 8.5,
        "EmployeeID": 10031
    },
    {
        "FirstName": "Michael",
        "LastName": "Jones",
        "Email": "michael.jones@company.com",
        "Phone": "+1-475-448-5969",
        "Department": "Sales",
        "Role": "Designer",
        "Location": "Austin, USA",
        "HireDate": new Date(1596856301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10032.jpg",
        "Skills": [
            "Python",
            "Node.js",
            "Java"
        ],
        "PerformanceScore": 82,
        "LastReviewDate": new Date(1738725101524),
        "ManagerId": "EMP-163",
        "LinkedIn": "linkedin.com/in/michael32",
        "Experience": 5.0,
        "EmployeeID": 10032
    },
    {
        "FirstName": "John",
        "LastName": "Jones",
        "Email": "john.jones@company.com",
        "Phone": "+1-507-287-1800",
        "Department": "Sales",
        "Role": "Developer",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1439349101524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10033.jpg",
        "Skills": [
            "Java",
            "SAP",
            "Leadership"
        ],
        "PerformanceScore": 95,
        "LastReviewDate": new Date(1743736301524),
        "ManagerId": "EMP-165",
        "LinkedIn": "linkedin.com/in/john33",
        "Experience": 10.0,
        "EmployeeID": 10033
    },
    {
        "FirstName": "Michael",
        "LastName": "Martinez",
        "Email": "michael.martinez@company.com",
        "Phone": "+1-114-564-8694",
        "Department": "Support",
        "Role": "QA Analyst",
        "Location": "Chicago, USA",
        "HireDate": new Date(1622344301524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10034.jpg",
        "Skills": [
            "Leadership",
            "Python",
            "SEO"
        ],
        "PerformanceScore": 50,
        "LastReviewDate": new Date(1750043501524),
        "ManagerId": "EMP-149",
        "LinkedIn": "linkedin.com/in/michael34",
        "Experience": 4.2,
        "EmployeeID": 10034
    },
    {
        "FirstName": "James",
        "LastName": "Hernandez",
        "Email": "james.hernandez@company.com",
        "Phone": "+1-329-646-3487",
        "Department": "Engineering",
        "Role": "Manager",
        "Location": "Seattle, USA",
        "HireDate": new Date(1479870701524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10035.jpg",
        "Skills": [
            "SAP",
            "Communication",
            "Java"
        ],
        "PerformanceScore": 100,
        "LastReviewDate": new Date(1745118701524),
        "ManagerId": "EMP-188",
        "LinkedIn": "linkedin.com/in/james35",
        "Experience": 8.7,
        "EmployeeID": 10035
    },
    {
        "FirstName": "Olivia",
        "LastName": "Miller",
        "Email": "olivia.miller@company.com",
        "Phone": "+1-238-736-1440",
        "Department": "Support",
        "Role": "Analyst",
        "Location": "Chicago, USA",
        "HireDate": new Date(1645758701524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10036.jpg",
        "Skills": [
            "Java",
            "Leadership",
            "SEO"
        ],
        "PerformanceScore": 76,
        "LastReviewDate": new Date(1733973101524),
        "ManagerId": "EMP-160",
        "LinkedIn": "linkedin.com/in/olivia36",
        "Experience": 3.4,
        "EmployeeID": 10036
    },
    {
        "FirstName": "Emily",
        "LastName": "Martinez",
        "Email": "emily.martinez@company.com",
        "Phone": "+1-240-648-8945",
        "Department": "HR",
        "Role": "Accountant",
        "Location": "Austin, USA",
        "HireDate": new Date(1529464301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10037.jpg",
        "Skills": [
            "Leadership",
            "React",
            "Python"
        ],
        "PerformanceScore": 63,
        "LastReviewDate": new Date(1737861101524),
        "ManagerId": "EMP-110",
        "LinkedIn": "linkedin.com/in/emily37",
        "Experience": 7.1,
        "EmployeeID": 10037
    },
    {
        "FirstName": "Emily",
        "LastName": "Hernandez",
        "Email": "emily.hernandez@company.com",
        "Phone": "+1-393-621-1817",
        "Department": "HR",
        "Role": "Analyst",
        "Location": "Austin, USA",
        "HireDate": new Date(1655435501524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10038.jpg",
        "Skills": [
            "Node.js",
            "SEO",
            "SAP"
        ],
        "PerformanceScore": 97,
        "LastReviewDate": new Date(1741317101524),
        "ManagerId": "EMP-130",
        "LinkedIn": "linkedin.com/in/emily38",
        "Experience": 3.1,
        "EmployeeID": 10038
    },
    {
        "FirstName": "Emily",
        "LastName": "Johnson",
        "Email": "emily.johnson@company.com",
        "Phone": "+1-327-717-8558",
        "Department": "Support",
        "Role": "Manager",
        "Location": "New York, USA",
        "HireDate": new Date(1585192301524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10039.jpg",
        "Skills": [
            "Node.js",
            "SEO",
            "Java"
        ],
        "PerformanceScore": 52,
        "LastReviewDate": new Date(1746155501524),
        "ManagerId": "EMP-108",
        "LinkedIn": "linkedin.com/in/emily39",
        "Experience": 5.3,
        "EmployeeID": 10039
    },
    {
        "FirstName": "Daniel",
        "LastName": "Jones",
        "Email": "daniel.jones@company.com",
        "Phone": "+1-558-212-1429",
        "Department": "HR",
        "Role": "Recruiter",
        "Location": "Chicago, USA",
        "HireDate": new Date(1705288301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10040.jpg",
        "Skills": [
            "Communication",
            "SAP",
            "SEO"
        ],
        "PerformanceScore": 86,
        "LastReviewDate": new Date(1722049901524),
        "ManagerId": "EMP-133",
        "LinkedIn": "linkedin.com/in/daniel40",
        "Experience": 1.5,
        "EmployeeID": 10040
    },
    {
        "FirstName": "Emma",
        "LastName": "Brown",
        "Email": "emma.brown@company.com",
        "Phone": "+1-463-678-6817",
        "Department": "Sales",
        "Role": "Devops Engineer",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1551755501524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10041.jpg",
        "Skills": [
            "Java",
            "Communication",
            "React"
        ],
        "PerformanceScore": 60,
        "LastReviewDate": new Date(1728702701524),
        "ManagerId": "EMP-105",
        "LinkedIn": "linkedin.com/in/emma41",
        "Experience": 6.4,
        "EmployeeID": 10041
    },
    {
        "FirstName": "James",
        "LastName": "Garcia",
        "Email": "james.garcia@company.com",
        "Phone": "+1-294-283-9047",
        "Department": "Finance",
        "Role": "Developer",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1517454701524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10042.jpg",
        "Skills": [
            "Leadership",
            "Java",
            "Communication"
        ],
        "PerformanceScore": 92,
        "LastReviewDate": new Date(1750561901524),
        "ManagerId": "EMP-179",
        "LinkedIn": "linkedin.com/in/james42",
        "Experience": 7.5,
        "EmployeeID": 10042
    },
    {
        "FirstName": "Michael",
        "LastName": "Hernandez",
        "Email": "michael.hernandez@company.com",
        "Phone": "+1-960-426-9053",
        "Department": "Sales",
        "Role": "Analyst",
        "Location": "Seattle, USA",
        "HireDate": new Date(1585537901524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10043.jpg",
        "Skills": [
            "Java",
            "SAP",
            "React"
        ],
        "PerformanceScore": 95,
        "LastReviewDate": new Date(1725333101524),
        "ManagerId": "EMP-181",
        "LinkedIn": "linkedin.com/in/michael43",
        "Experience": 5.3,
        "EmployeeID": 10043
    },
    {
        "FirstName": "John",
        "LastName": "Martinez",
        "Email": "john.martinez@company.com",
        "Phone": "+1-206-115-9060",
        "Department": "Finance",
        "Role": "Designer",
        "Location": "Chicago, USA",
        "HireDate": new Date(1501816301524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10044.jpg",
        "Skills": [
            "Node.js",
            "React",
            "Java"
        ],
        "PerformanceScore": 62,
        "LastReviewDate": new Date(1726197101524),
        "ManagerId": "EMP-110",
        "LinkedIn": "linkedin.com/in/john44",
        "Experience": 8.0,
        "EmployeeID": 10044
    },
    {
        "FirstName": "James",
        "LastName": "Davis",
        "Email": "james.davis@company.com",
        "Phone": "+1-130-791-9681",
        "Department": "Engineering",
        "Role": "Analyst",
        "Location": "Seattle, USA",
        "HireDate": new Date(1470625901524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10045.jpg",
        "Skills": [
            "Communication",
            "Node.js",
            "Java"
        ],
        "PerformanceScore": 73,
        "LastReviewDate": new Date(1722222701524),
        "ManagerId": "EMP-176",
        "LinkedIn": "linkedin.com/in/james45",
        "Experience": 9.0,
        "EmployeeID": 10045
    },
    {
        "FirstName": "Michael",
        "LastName": "Smith",
        "Email": "michael.smith@company.com",
        "Phone": "+1-545-530-4256",
        "Department": "Sales",
        "Role": "Accountant",
        "Location": "San Francisco, USA",
        "HireDate": new Date(1513134701524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10046.jpg",
        "Skills": [
            "Leadership",
            "React",
            "Communication"
        ],
        "PerformanceScore": 88,
        "LastReviewDate": new Date(1725073901524),
        "ManagerId": "EMP-167",
        "LinkedIn": "linkedin.com/in/michael46",
        "Experience": 7.6,
        "EmployeeID": 10046
    },
    {
        "FirstName": "David",
        "LastName": "Davis",
        "Email": "david.davis@company.com",
        "Phone": "+1-806-351-2164",
        "Department": "Sales",
        "Role": "Recruiter",
        "Location": "Seattle, USA",
        "HireDate": new Date(1645845101524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10047.jpg",
        "Skills": [
            "Java",
            "Communication",
            "Leadership"
        ],
        "PerformanceScore": 99,
        "LastReviewDate": new Date(1733195501524),
        "ManagerId": "EMP-180",
        "LinkedIn": "linkedin.com/in/david47",
        "Experience": 3.4,
        "EmployeeID": 10047
    },
    {
        "FirstName": "Sarah",
        "LastName": "Miller",
        "Email": "sarah.miller@company.com",
        "Phone": "+1-180-102-1100",
        "Department": "Engineering",
        "Role": "QA Analyst",
        "Location": "Austin, USA",
        "HireDate": new Date(1444533101524),
        "IsActive": true,
        "ProfileImage": "https://company.com/images/emp10048.jpg",
        "Skills": [
            "Java",
            "Python",
            "Node.js"
        ],
        "PerformanceScore": 87,
        "LastReviewDate": new Date(1741576301524),
        "ManagerId": "EMP-195",
        "LinkedIn": "linkedin.com/in/sarah48",
        "Experience": 9.8,
        "EmployeeID": 10048
    },
    {
        "FirstName": "Michael",
        "LastName": "Garcia",
        "Email": "michael.garcia@company.com",
        "Phone": "+1-107-621-8758",
        "Department": "Finance",
        "Role": "Accountant",
        "Location": "Chicago, USA",
        "HireDate": new Date(1675307501524),
        "IsActive": false,
        "ProfileImage": "https://company.com/images/emp10049.jpg",
        "Skills": [
            "Communication",
            "React",
            "Node.js"
        ],
        "PerformanceScore": 97,
        "LastReviewDate": new Date(1722654701524),
        "ManagerId": "EMP-168",
        "LinkedIn": "linkedin.com/in/michael49",
        "Experience": 2.5,
        "EmployeeID": 10049
    }
]