export const employeeInformation = [
  { EmployeeID: 'EMP-101', Name: 'John Smith', Designation: 'Software Engineer', DateOfJoining: new Date(2020, 5, 12), Location: 'WFH', isLocked: false, EmployeeStatus: 'Available', Email: 'john.smith@example.com', PhoneNumber: '555-123-4567', Department: 'Web Development', EmploymentType: 'Full-Time', ReportingPerson: 'David Thompson', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-102', Name: 'James Miller', Designation: 'UI/UX Designer', DateOfJoining: new Date(2019, 3, 8), Location: 'Alpha Office', isLocked: false, EmployeeStatus: 'Available', Email: 'emily.johnson@example.com', PhoneNumber: '555-123-4567', Department: 'Design', EmploymentType: 'Full-Time', ReportingPerson: 'Emily Johnson', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-103', Name: 'Michael Brown', Designation: 'QA Engineer', DateOfJoining: new Date(2021, 1, 15), Location: 'Beta Office', isLocked: true, EmployeeStatus: 'Available', Email: 'michael.brown@example.com', PhoneNumber: '555-123-4567', Department: 'Testing', EmploymentType: 'Full-Time', ReportingPerson: 'Ella Martin', ReportingManager: 'James Wilson' },
  { EmployeeID: 'EMP-104', Name: 'Sarah Davis', Designation: 'HR Specialist', DateOfJoining: new Date(2018, 10, 20), Location: 'WFH', isLocked: false, EmployeeStatus: 'Available', Email: 'sarah.davis@example.com', PhoneNumber: '555-123-4567', Department: 'HR', EmploymentType: 'Full-Time', ReportingPerson: 'William Clark', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-105', Name: 'James Wilson', Designation: 'Software Engineer', DateOfJoining: new Date(2017, 7, 5), Location: 'Alpha Office', isLocked: false, EmployeeStatus: 'Available', Email: 'james.wilson@example.com', PhoneNumber: '555-123-4567', Department: 'UI and UX', EmploymentType: 'Full-Time', ReportingPerson: 'David Thompson', ReportingManager: 'David Thompson' }, 
  { EmployeeID: 'EMP-106', Name: 'Olivia Martinez', Designation: 'Software Engineer', DateOfJoining: new Date(2022, 2, 28), Location: 'Gamma Office', isLocked: false, EmployeeStatus: 'Available', Email: 'olivia.martinez@example.com', PhoneNumber: '555-123-4567', Department: 'Finance', EmploymentType: 'Full-Time', ReportingPerson: 'Henry Jackson', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-107', Name: 'William Anderson', Designation: 'Technical Support Specialist', DateOfJoining: new Date(2020, 11, 10), Location: 'WFH', isLocked: true, EmployeeStatus: 'Not Available', Email: 'william.anderson@example.com', PhoneNumber: '555-123-4567', Department: 'Front office', EmploymentType: 'Full-Time', ReportingPerson: 'Matthew Harris', ReportingManager: 'Chloe White' }, 
  { EmployeeID: 'EMP-108', Name: 'Sophia Thomas', Designation: 'UI/UX Designer', DateOfJoining: new Date(2019, 6, 18), Location: 'Beta Office', isLocked: false, EmployeeStatus: 'Available', Email: 'sophia.thomas@example.com', PhoneNumber: '555-123-4567', Department: 'Design', EmploymentType: 'Full-Time', ReportingPerson: 'Emily Johnson', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-109', Name: 'Daniel Taylor', Designation: 'QA Engineer', DateOfJoining: new Date(2021, 4, 22), Location: 'Alpha Office', isLocked: false, EmployeeStatus: 'Available', Email: 'daniel.taylor@example.com', PhoneNumber: '555-123-4567', Department: 'Testing', EmploymentType: 'Full-Time', ReportingPerson: 'Ella Martin', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-110', Name: 'Grace Moore', Designation: 'HR Specialist', DateOfJoining: new Date(2018, 9, 30), Location: 'WFH', isLocked: false, EmployeeStatus: 'Available', Email: 'grace.moore@example.com', PhoneNumber: '555-123-4567', Department: 'HR', EmploymentType: 'Full-Time', ReportingPerson: 'William Clark', ReportingManager: 'James Wilson' },
  { EmployeeID: 'EMP-111', Name: 'Henry Jackson', Designation: 'Software Engineer', DateOfJoining: new Date(2020, 8, 14), Location: 'Gamma Office', isLocked: false, EmployeeStatus: 'Available', Email: 'henry.jackson@example.com', PhoneNumber: '555-123-4567', Department: 'Web Development', EmploymentType: 'Full-Time', ReportingPerson: 'David Thompson', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-112', Name: 'Chloe White', Designation: 'QA Engineer', DateOfJoining: new Date(2017, 12, 1), Location: 'WFH', isLocked: true, EmployeeStatus: 'Not Available', Email: 'chloe.white@example.com', PhoneNumber: '555-123-4567', Department: 'Testing', EmploymentType: 'Full-Time', ReportingPerson: 'Ella Martin', ReportingManager: 'David Thompson' }, 
  { EmployeeID: 'EMP-113', Name: 'Matthew Harris', Designation: 'Technical Support Specialist', DateOfJoining: new Date(2022, 5, 9), Location: 'Beta Office', isLocked: false, EmployeeStatus: 'Available', Email: 'matthew.harris@example.com', PhoneNumber: '555-123-4567', Department: 'Web Development', EmploymentType: 'Full-Time', ReportingPerson: 'David Thompson', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-114', Name: 'Ella Martin', Designation: 'QA Engineer', DateOfJoining: new Date(2021, 7, 19), Location: 'Alpha Office', isLocked: false, EmployeeStatus: 'Available', Email: 'ella.martin@example.com', PhoneNumber: '555-123-4567', Department: 'Testing', EmploymentType: 'Full-Time', ReportingPerson: 'Ella Martin', ReportingManager: 'James Wilson' }, 
  { EmployeeID: 'EMP-115', Name: 'Robert Davis', Designation: 'Software Engineer', DateOfJoining: new Date(2019, 2, 25), Location: 'WFH', isLocked: false, EmployeeStatus: 'Available', Email: 'david.thompson@example.com', PhoneNumber: '555-123-4567', Department: 'Web Development', EmploymentType: 'Full-Time', ReportingPerson: 'David Thompson', ReportingManager: 'James Wilson' } 
];