
export interface PatientRecord {
  PatientID: number;
  FirstName: string;
  LastName: string;
  DateOfBirth: Date;
  Gender: string;
  ContactInfo: string;
  Address: string;
  City: string;
  State: string;
  PostalCode: string;
  Country: string;
  LastVisitDate: Date;
  InsuranceProvider: string;
  MedicalCondition: string;
  VisitCount: number;
}

export const medicalHistory: PatientRecord[] =[
  {
    "PatientID": 1000,
    "FirstName": "Bob",
    "LastName": "Johnson",
    "DateOfBirth": new Date(867369600000),
    "Gender": "Female",
    "ContactInfo": "user1@example.com",
    "Address": "980 Main St",
    "City": "Houston",
    "State": "IL",
    "PostalCode": "77478",
    "Country": "USA",
    "LastVisitDate": new Date(1635033600000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 10
  },
  {
    "PatientID": 1001,
    "FirstName": "Fiona",
    "LastName": "Garcia",
    "DateOfBirth": new Date(1522368000000),
    "Gender": "Other",
    "ContactInfo": "user2@example.com",
    "Address": "289 Main St",
    "City": "New York",
    "State": "IL",
    "PostalCode": "99285",
    "Country": "USA",
    "LastVisitDate": new Date(1657929600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Arthritis",
    "VisitCount": 1
  },
  {
    "PatientID": 1002,
    "FirstName": "Diana",
    "LastName": "Brown",
    "DateOfBirth": new Date(-413596800000),
    "Gender": "Other",
    "ContactInfo": "user3@example.com",
    "Address": "395 Main St",
    "City": "Los Angeles",
    "State": "CA",
    "PostalCode": "88819",
    "Country": "USA",
    "LastVisitDate": new Date(1694476800000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Hypertension",
    "VisitCount": 5
  },
  {
    "PatientID": 1003,
    "FirstName": "Alice",
    "LastName": "Garcia",
    "DateOfBirth": new Date(1225929600000),
    "Gender": "Male",
    "ContactInfo": "user4@example.com",
    "Address": "803 Main St",
    "City": "Phoenix",
    "State": "AZ",
    "PostalCode": "50387",
    "Country": "USA",
    "LastVisitDate": new Date(1626220800000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Arthritis",
    "VisitCount": 8
  },
  {
    "PatientID": 1004,
    "FirstName": "Fiona",
    "LastName": "Williams",
    "DateOfBirth": new Date(820886400000),
    "Gender": "Female",
    "ContactInfo": "user5@example.com",
    "Address": "983 Main St",
    "City": "Phoenix",
    "State": "AZ",
    "PostalCode": "80802",
    "Country": "USA",
    "LastVisitDate": new Date(1644969600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Hypertension",
    "VisitCount": 5
  },
  {
    "PatientID": 1005,
    "FirstName": "Fiona",
    "LastName": "Williams",
    "DateOfBirth": new Date(393033600000),
    "Gender": "Other",
    "ContactInfo": "user6@example.com",
    "Address": "805 Main St",
    "City": "Chicago",
    "State": "IL",
    "PostalCode": "48938",
    "Country": "USA",
    "LastVisitDate": new Date(1613606400000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 7
  },
  {
    "PatientID": 1006,
    "FirstName": "Ethan",
    "LastName": "Johnson",
    "DateOfBirth": new Date(433728000000),
    "Gender": "Female",
    "ContactInfo": "user7@example.com",
    "Address": "582 Main St",
    "City": "Phoenix",
    "State": "TX",
    "PostalCode": "98378",
    "Country": "USA",
    "LastVisitDate": new Date(1686528000000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Arthritis",
    "VisitCount": 6
  },
  {
    "PatientID": 1007,
    "FirstName": "Bob",
    "LastName": "Smith",
    "DateOfBirth": new Date(-441158400000),
    "Gender": "Other",
    "ContactInfo": "user8@example.com",
    "Address": "216 Main St",
    "City": "Phoenix",
    "State": "TX",
    "PostalCode": "39781",
    "Country": "USA",
    "LastVisitDate": new Date(1668988800000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Hypertension",
    "VisitCount": 10
  },
  {
    "PatientID": 1008,
    "FirstName": "Charlie",
    "LastName": "Johnson",
    "DateOfBirth": new Date(1456012800000),
    "Gender": "Female",
    "ContactInfo": "user9@example.com",
    "Address": "680 Main St",
    "City": "Phoenix",
    "State": "AZ",
    "PostalCode": "29113",
    "Country": "USA",
    "LastVisitDate": new Date(1668470400000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Arthritis",
    "VisitCount": 6
  },
  {
    "PatientID": 1009,
    "FirstName": "Ethan",
    "LastName": "Smith",
    "DateOfBirth": new Date(222393600000),
    "Gender": "Male",
    "ContactInfo": "user10@example.com",
    "Address": "173 Main St",
    "City": "New York",
    "State": "IL",
    "PostalCode": "76512",
    "Country": "USA",
    "LastVisitDate": new Date(1607385600000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Arthritis",
    "VisitCount": 10
  },
  {
    "PatientID": 1010,
    "FirstName": "Bob",
    "LastName": "Brown",
    "DateOfBirth": new Date(1468108800000),
    "Gender": "Other",
    "ContactInfo": "user11@example.com",
    "Address": "181 Main St",
    "City": "Los Angeles",
    "State": "TX",
    "PostalCode": "89131",
    "Country": "USA",
    "LastVisitDate": new Date(1591660800000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 3
  },
  {
    "PatientID": 1011,
    "FirstName": "Ethan",
    "LastName": "Williams",
    "DateOfBirth": new Date(1346198400000),
    "Gender": "Other",
    "ContactInfo": "user12@example.com",
    "Address": "404 Main St",
    "City": "New York",
    "State": "TX",
    "PostalCode": "50984",
    "Country": "USA",
    "LastVisitDate": new Date(1578009600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Hypertension",
    "VisitCount": 8
  },
  {
    "PatientID": 1012,
    "FirstName": "Charlie",
    "LastName": "Brown",
    "DateOfBirth": new Date(784339200000),
    "Gender": "Male",
    "ContactInfo": "user13@example.com",
    "Address": "678 Main St",
    "City": "Chicago",
    "State": "AZ",
    "PostalCode": "82637",
    "Country": "USA",
    "LastVisitDate": new Date(1616889600000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Asthma",
    "VisitCount": 5
  },
  {
    "PatientID": 1013,
    "FirstName": "Diana",
    "LastName": "Brown",
    "DateOfBirth": new Date(298684800000),
    "Gender": "Female",
    "ContactInfo": "user14@example.com",
    "Address": "805 Main St",
    "City": "Los Angeles",
    "State": "NY",
    "PostalCode": "41380",
    "Country": "USA",
    "LastVisitDate": new Date(1597276800000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Arthritis",
    "VisitCount": 2
  },
  {
    "PatientID": 1014,
    "FirstName": "Alice",
    "LastName": "Smith",
    "DateOfBirth": new Date(14083200000),
    "Gender": "Other",
    "ContactInfo": "user15@example.com",
    "Address": "215 Main St",
    "City": "New York",
    "State": "NY",
    "PostalCode": "85446",
    "Country": "USA",
    "LastVisitDate": new Date(1632441600000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Diabetes",
    "VisitCount": 3
  },
  {
    "PatientID": 1015,
    "FirstName": "Fiona",
    "LastName": "Williams",
    "DateOfBirth": new Date(-617328000000),
    "Gender": "Male",
    "ContactInfo": "user16@example.com",
    "Address": "458 Main St",
    "City": "Los Angeles",
    "State": "TX",
    "PostalCode": "33566",
    "Country": "USA",
    "LastVisitDate": new Date(1706313600000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Arthritis",
    "VisitCount": 10
  },
  {
    "PatientID": 1016,
    "FirstName": "Bob",
    "LastName": "Brown",
    "DateOfBirth": new Date(1484784000000),
    "Gender": "Male",
    "ContactInfo": "user17@example.com",
    "Address": "165 Main St",
    "City": "New York",
    "State": "AZ",
    "PostalCode": "16480",
    "Country": "USA",
    "LastVisitDate": new Date(1649721600000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Diabetes",
    "VisitCount": 8
  },
  {
    "PatientID": 1017,
    "FirstName": "Bob",
    "LastName": "Garcia",
    "DateOfBirth": new Date(417312000000),
    "Gender": "Male",
    "ContactInfo": "user18@example.com",
    "Address": "528 Main St",
    "City": "Chicago",
    "State": "TX",
    "PostalCode": "56694",
    "Country": "USA",
    "LastVisitDate": new Date(1622073600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Diabetes",
    "VisitCount": 1
  },
  {
    "PatientID": 1018,
    "FirstName": "Fiona",
    "LastName": "Smith",
    "DateOfBirth": new Date(953769600000),
    "Gender": "Male",
    "ContactInfo": "user19@example.com",
    "Address": "193 Main St",
    "City": "New York",
    "State": "AZ",
    "PostalCode": "67652",
    "Country": "USA",
    "LastVisitDate": new Date(1674864000000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Asthma",
    "VisitCount": 9
  },
  {
    "PatientID": 1019,
    "FirstName": "Alice",
    "LastName": "Garcia",
    "DateOfBirth": new Date(1190246400000),
    "Gender": "Male",
    "ContactInfo": "user20@example.com",
    "Address": "461 Main St",
    "City": "Phoenix",
    "State": "IL",
    "PostalCode": "20799",
    "Country": "USA",
    "LastVisitDate": new Date(1654819200000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Asthma",
    "VisitCount": 9
  },
  {
    "PatientID": 1020,
    "FirstName": "Alice",
    "LastName": "Williams",
    "DateOfBirth": new Date(-8985600000),
    "Gender": "Male",
    "ContactInfo": "user21@example.com",
    "Address": "960 Main St",
    "City": "Chicago",
    "State": "AZ",
    "PostalCode": "76329",
    "Country": "USA",
    "LastVisitDate": new Date(1638403200000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Diabetes",
    "VisitCount": 9
  },
  {
    "PatientID": 1021,
    "FirstName": "Ethan",
    "LastName": "Johnson",
    "DateOfBirth": new Date(364780800000),
    "Gender": "Other",
    "ContactInfo": "user22@example.com",
    "Address": "605 Main St",
    "City": "Phoenix",
    "State": "AZ",
    "PostalCode": "45965",
    "Country": "USA",
    "LastVisitDate": new Date(1702684800000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Asthma",
    "VisitCount": 4
  },
  {
    "PatientID": 1022,
    "FirstName": "Charlie",
    "LastName": "Smith",
    "DateOfBirth": new Date(708998400000),
    "Gender": "Male",
    "ContactInfo": "user23@example.com",
    "Address": "630 Main St",
    "City": "Chicago",
    "State": "NY",
    "PostalCode": "12231",
    "Country": "USA",
    "LastVisitDate": new Date(1688083200000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 1
  },
  {
    "PatientID": 1023,
    "FirstName": "Bob",
    "LastName": "Williams",
    "DateOfBirth": new Date(-472089600000),
    "Gender": "Female",
    "ContactInfo": "user24@example.com",
    "Address": "992 Main St",
    "City": "Chicago",
    "State": "NY",
    "PostalCode": "20214",
    "Country": "USA",
    "LastVisitDate": new Date(1628812800000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Asthma",
    "VisitCount": 6
  },
  {
    "PatientID": 1024,
    "FirstName": "Diana",
    "LastName": "Smith",
    "DateOfBirth": new Date(-40953600000),
    "Gender": "Other",
    "ContactInfo": "user25@example.com",
    "Address": "949 Main St",
    "City": "Houston",
    "State": "IL",
    "PostalCode": "14434",
    "Country": "USA",
    "LastVisitDate": new Date(1667520000000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Arthritis",
    "VisitCount": 5
  },
  {
    "PatientID": 1025,
    "FirstName": "Fiona",
    "LastName": "Brown",
    "DateOfBirth": new Date(13564800000),
    "Gender": "Other",
    "ContactInfo": "user26@example.com",
    "Address": "267 Main St",
    "City": "Houston",
    "State": "CA",
    "PostalCode": "89824",
    "Country": "USA",
    "LastVisitDate": new Date(1635984000000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Arthritis",
    "VisitCount": 4
  },
  {
    "PatientID": 1026,
    "FirstName": "Alice",
    "LastName": "Garcia",
    "DateOfBirth": new Date(792720000000),
    "Gender": "Male",
    "ContactInfo": "user27@example.com",
    "Address": "281 Main St",
    "City": "Chicago",
    "State": "IL",
    "PostalCode": "23366",
    "Country": "USA",
    "LastVisitDate": new Date(1644883200000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Asthma",
    "VisitCount": 6
  },
  {
    "PatientID": 1027,
    "FirstName": "Ethan",
    "LastName": "Johnson",
    "DateOfBirth": new Date(86745600000),
    "Gender": "Other",
    "ContactInfo": "user28@example.com",
    "Address": "114 Main St",
    "City": "Los Angeles",
    "State": "IL",
    "PostalCode": "10173",
    "Country": "USA",
    "LastVisitDate": new Date(1617062400000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 1
  },
  {
    "PatientID": 1028,
    "FirstName": "Bob",
    "LastName": "Johnson",
    "DateOfBirth": new Date(372384000000),
    "Gender": "Female",
    "ContactInfo": "user29@example.com",
    "Address": "134 Main St",
    "City": "Phoenix",
    "State": "IL",
    "PostalCode": "69041",
    "Country": "USA",
    "LastVisitDate": new Date(1700611200000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Asthma",
    "VisitCount": 10
  },
  {
    "PatientID": 1029,
    "FirstName": "Diana",
    "LastName": "Johnson",
    "DateOfBirth": new Date(870220800000),
    "Gender": "Male",
    "ContactInfo": "user30@example.com",
    "Address": "444 Main St",
    "City": "Houston",
    "State": "CA",
    "PostalCode": "45749",
    "Country": "USA",
    "LastVisitDate": new Date(1616544000000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Hypertension",
    "VisitCount": 5
  },
  {
    "PatientID": 1030,
    "FirstName": "Charlie",
    "LastName": "Brown",
    "DateOfBirth": new Date(399945600000),
    "Gender": "Other",
    "ContactInfo": "user31@example.com",
    "Address": "585 Main St",
    "City": "Los Angeles",
    "State": "NY",
    "PostalCode": "68259",
    "Country": "USA",
    "LastVisitDate": new Date(1598745600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Hypertension",
    "VisitCount": 7
  },
  {
    "PatientID": 1031,
    "FirstName": "Ethan",
    "LastName": "Williams",
    "DateOfBirth": new Date(-183340800000),
    "Gender": "Female",
    "ContactInfo": "user32@example.com",
    "Address": "541 Main St",
    "City": "Chicago",
    "State": "IL",
    "PostalCode": "57767",
    "Country": "USA",
    "LastVisitDate": new Date(1644796800000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Asthma",
    "VisitCount": 3
  },
  {
    "PatientID": 1032,
    "FirstName": "Bob",
    "LastName": "Williams",
    "DateOfBirth": new Date(1462579200000),
    "Gender": "Male",
    "ContactInfo": "user33@example.com",
    "Address": "960 Main St",
    "City": "Phoenix",
    "State": "AZ",
    "PostalCode": "85910",
    "Country": "USA",
    "LastVisitDate": new Date(1597968000000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Hypertension",
    "VisitCount": 9
  },
  {
    "PatientID": 1033,
    "FirstName": "Bob",
    "LastName": "Garcia",
    "DateOfBirth": new Date(1263168000000),
    "Gender": "Other",
    "ContactInfo": "user34@example.com",
    "Address": "657 Main St",
    "City": "Houston",
    "State": "CA",
    "PostalCode": "85416",
    "Country": "USA",
    "LastVisitDate": new Date(1691712000000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Hypertension",
    "VisitCount": 8
  },
  {
    "PatientID": 1034,
    "FirstName": "Ethan",
    "LastName": "Jones",
    "DateOfBirth": new Date(-243043200000),
    "Gender": "Male",
    "ContactInfo": "user35@example.com",
    "Address": "871 Main St",
    "City": "New York",
    "State": "CA",
    "PostalCode": "37323",
    "Country": "USA",
    "LastVisitDate": new Date(1577923200000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Diabetes",
    "VisitCount": 1
  },
  {
    "PatientID": 1035,
    "FirstName": "Diana",
    "LastName": "Smith",
    "DateOfBirth": new Date(633830400000),
    "Gender": "Male",
    "ContactInfo": "user36@example.com",
    "Address": "548 Main St",
    "City": "Los Angeles",
    "State": "AZ",
    "PostalCode": "69317",
    "Country": "USA",
    "LastVisitDate": new Date(1602460800000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Asthma",
    "VisitCount": 4
  },
  {
    "PatientID": 1036,
    "FirstName": "Fiona",
    "LastName": "Johnson",
    "DateOfBirth": new Date(-368668800000),
    "Gender": "Other",
    "ContactInfo": "user37@example.com",
    "Address": "943 Main St",
    "City": "Chicago",
    "State": "TX",
    "PostalCode": "90077",
    "Country": "USA",
    "LastVisitDate": new Date(1618185600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Arthritis",
    "VisitCount": 8
  },
  {
    "PatientID": 1037,
    "FirstName": "Bob",
    "LastName": "Jones",
    "DateOfBirth": new Date(1483228800000),
    "Gender": "Other",
    "ContactInfo": "user38@example.com",
    "Address": "607 Main St",
    "City": "Houston",
    "State": "IL",
    "PostalCode": "29113",
    "Country": "USA",
    "LastVisitDate": new Date(1637712000000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 10
  },
  {
    "PatientID": 1038,
    "FirstName": "Fiona",
    "LastName": "Williams",
    "DateOfBirth": new Date(509414400000),
    "Gender": "Male",
    "ContactInfo": "user39@example.com",
    "Address": "209 Main St",
    "City": "Phoenix",
    "State": "CA",
    "PostalCode": "33811",
    "Country": "USA",
    "LastVisitDate": new Date(1695859200000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 9
  },
  {
    "PatientID": 1039,
    "FirstName": "Bob",
    "LastName": "Jones",
    "DateOfBirth": new Date(1400457600000),
    "Gender": "Female",
    "ContactInfo": "user40@example.com",
    "Address": "905 Main St",
    "City": "Chicago",
    "State": "AZ",
    "PostalCode": "67313",
    "Country": "USA",
    "LastVisitDate": new Date(1702944000000),
    "InsuranceProvider": "UnitedHealth",
    "MedicalCondition": "Asthma",
    "VisitCount": 6
  },
  {
    "PatientID": 1040,
    "FirstName": "Bob",
    "LastName": "Garcia",
    "DateOfBirth": new Date(261014400000),
    "Gender": "Female",
    "ContactInfo": "user41@example.com",
    "Address": "992 Main St",
    "City": "Phoenix",
    "State": "TX",
    "PostalCode": "71127",
    "Country": "USA",
    "LastVisitDate": new Date(1649635200000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 9
  },
  {
    "PatientID": 1041,
    "FirstName": "Fiona",
    "LastName": "Brown",
    "DateOfBirth": new Date(-111283200000),
    "Gender": "Male",
    "ContactInfo": "user42@example.com",
    "Address": "216 Main St",
    "City": "Houston",
    "State": "CA",
    "PostalCode": "88061",
    "Country": "USA",
    "LastVisitDate": new Date(1616457600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Diabetes",
    "VisitCount": 2
  },
  {
    "PatientID": 1042,
    "FirstName": "Ethan",
    "LastName": "Brown",
    "DateOfBirth": new Date(471830400000),
    "Gender": "Other",
    "ContactInfo": "user43@example.com",
    "Address": "692 Main St",
    "City": "Chicago",
    "State": "NY",
    "PostalCode": "16254",
    "Country": "USA",
    "LastVisitDate": new Date(1684627200000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Asthma",
    "VisitCount": 2
  },
  {
    "PatientID": 1043,
    "FirstName": "Ethan",
    "LastName": "Jones",
    "DateOfBirth": new Date(-169084800000),
    "Gender": "Female",
    "ContactInfo": "user44@example.com",
    "Address": "366 Main St",
    "City": "Houston",
    "State": "IL",
    "PostalCode": "93225",
    "Country": "USA",
    "LastVisitDate": new Date(1690070400000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Diabetes",
    "VisitCount": 7
  },
  {
    "PatientID": 1044,
    "FirstName": "Bob",
    "LastName": "Brown",
    "DateOfBirth": new Date(1226620800000),
    "Gender": "Female",
    "ContactInfo": "user45@example.com",
    "Address": "796 Main St",
    "City": "Houston",
    "State": "TX",
    "PostalCode": "51688",
    "Country": "USA",
    "LastVisitDate": new Date(1580688000000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Arthritis",
    "VisitCount": 8
  },
  {
    "PatientID": 1045,
    "FirstName": "Charlie",
    "LastName": "Johnson",
    "DateOfBirth": new Date(-627868800000),
    "Gender": "Male",
    "ContactInfo": "user46@example.com",
    "Address": "784 Main St",
    "City": "Houston",
    "State": "AZ",
    "PostalCode": "76171",
    "Country": "USA",
    "LastVisitDate": new Date(1592179200000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 3
  },
  {
    "PatientID": 1046,
    "FirstName": "Bob",
    "LastName": "Brown",
    "DateOfBirth": new Date(601171200000),
    "Gender": "Female",
    "ContactInfo": "user47@example.com",
    "Address": "464 Main St",
    "City": "Phoenix",
    "State": "TX",
    "PostalCode": "33049",
    "Country": "USA",
    "LastVisitDate": new Date(1613174400000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Arthritis",
    "VisitCount": 6
  },
  {
    "PatientID": 1047,
    "FirstName": "Fiona",
    "LastName": "Garcia",
    "DateOfBirth": new Date(-233366400000),
    "Gender": "Other",
    "ContactInfo": "user48@example.com",
    "Address": "704 Main St",
    "City": "Chicago",
    "State": "CA",
    "PostalCode": "53547",
    "Country": "USA",
    "LastVisitDate": new Date(1654473600000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Arthritis",
    "VisitCount": 1
  },
  {
    "PatientID": 1048,
    "FirstName": "Alice",
    "LastName": "Garcia",
    "DateOfBirth": new Date(-554083200000),
    "Gender": "Female",
    "ContactInfo": "user49@example.com",
    "Address": "436 Main St",
    "City": "New York",
    "State": "NY",
    "PostalCode": "26472",
    "Country": "USA",
    "LastVisitDate": new Date(1647561600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 7
  },
  {
    "PatientID": 1049,
    "FirstName": "Charlie",
    "LastName": "Smith",
    "DateOfBirth": new Date(1299196800000),
    "Gender": "Other",
    "ContactInfo": "user50@example.com",
    "Address": "778 Main St",
    "City": "Chicago",
    "State": "CA",
    "PostalCode": "45384",
    "Country": "USA",
    "LastVisitDate": new Date(1599264000000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Hypertension",
    "VisitCount": 7
  },
  {
    "PatientID": 1050,
    "FirstName": "Diana",
    "LastName": "Williams",
    "DateOfBirth": new Date(86832000000),
    "Gender": "Female",
    "ContactInfo": "user51@example.com",
    "Address": "120 Main St",
    "City": "Phoenix",
    "State": "NY",
    "PostalCode": "65626",
    "Country": "USA",
    "LastVisitDate": new Date(1701820800000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Hypertension",
    "VisitCount": 4
  },
  {
    "PatientID": 1051,
    "FirstName": "Alice",
    "LastName": "Jones",
    "DateOfBirth": new Date(761443200000),
    "Gender": "Female",
    "ContactInfo": "user52@example.com",
    "Address": "847 Main St",
    "City": "Chicago",
    "State": "AZ",
    "PostalCode": "76388",
    "Country": "USA",
    "LastVisitDate": new Date(1637971200000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Asthma",
    "VisitCount": 1
  },
  {
    "PatientID": 1052,
    "FirstName": "Fiona",
    "LastName": "Smith",
    "DateOfBirth": new Date(1276128000000),
    "Gender": "Male",
    "ContactInfo": "user53@example.com",
    "Address": "227 Main St",
    "City": "Chicago",
    "State": "AZ",
    "PostalCode": "55931",
    "Country": "USA",
    "LastVisitDate": new Date(1610496000000),
    "InsuranceProvider": "Cigna",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 1
  },
  {
    "PatientID": 1053,
    "FirstName": "Charlie",
    "LastName": "Garcia",
    "DateOfBirth": new Date(-496281600000),
    "Gender": "Other",
    "ContactInfo": "user54@example.com",
    "Address": "747 Main St",
    "City": "Los Angeles",
    "State": "AZ",
    "PostalCode": "95744",
    "Country": "USA",
    "LastVisitDate": new Date(1692230400000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 3
  },
  {
    "PatientID": 1054,
    "FirstName": "Charlie",
    "LastName": "Smith",
    "DateOfBirth": new Date(603936000000),
    "Gender": "Other",
    "ContactInfo": "user55@example.com",
    "Address": "399 Main St",
    "City": "New York",
    "State": "NY",
    "PostalCode": "15700",
    "Country": "USA",
    "LastVisitDate": new Date(1582329600000),
    "InsuranceProvider": "Aetna",
    "MedicalCondition": "Diabetes",
    "VisitCount": 4
  },
  {
    "PatientID": 1055,
    "FirstName": "Alice",
    "LastName": "Garcia",
    "DateOfBirth": new Date(1141948800000),
    "Gender": "Female",
    "ContactInfo": "user56@example.com",
    "Address": "568 Main St",
    "City": "Houston",
    "State": "NY",
    "PostalCode": "14473",
    "Country": "USA",
    "LastVisitDate": new Date(1673654400000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Hypertension",
    "VisitCount": 10
  },
  {
    "PatientID": 1056,
    "FirstName": "Charlie",
    "LastName": "Garcia",
    "DateOfBirth": new Date(80611200000),
    "Gender": "Other",
    "ContactInfo": "user57@example.com",
    "Address": "686 Main St",
    "City": "Houston",
    "State": "AZ",
    "PostalCode": "36483",
    "Country": "USA",
    "LastVisitDate": new Date(1675209600000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Hypertension",
    "VisitCount": 1
  },
  {
    "PatientID": 1057,
    "FirstName": "Bob",
    "LastName": "Johnson",
    "DateOfBirth": new Date(162259200000),
    "Gender": "Male",
    "ContactInfo": "user58@example.com",
    "Address": "345 Main St",
    "City": "New York",
    "State": "CA",
    "PostalCode": "32142",
    "Country": "USA",
    "LastVisitDate": new Date(1660435200000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 7
  },
  {
    "PatientID": 1058,
    "FirstName": "Diana",
    "LastName": "Jones",
    "DateOfBirth": new Date(-25142400000),
    "Gender": "Female",
    "ContactInfo": "user59@example.com",
    "Address": "841 Main St",
    "City": "Chicago",
    "State": "CA",
    "PostalCode": "39078",
    "Country": "USA",
    "LastVisitDate": new Date(1638662400000),
    "InsuranceProvider": "Blue Cross",
    "MedicalCondition": "Arthritis",
    "VisitCount": 2
  },
  {
    "PatientID": 1059,
    "FirstName": "Diana",
    "LastName": "Garcia",
    "DateOfBirth": new Date(-261964800000),
    "Gender": "Other",
    "ContactInfo": "user60@example.com",
    "Address": "898 Main St",
    "City": "New York",
    "State": "TX",
    "PostalCode": "81565",
    "Country": "USA",
    "LastVisitDate": new Date(1675123200000),
    "InsuranceProvider": "Kaiser",
    "MedicalCondition": "Heart Disease",
    "VisitCount": 3
  }
]