export const inventoryManagementData: object[] = [
  {
    "SKU": "PROD-001",
    "ProductName": "Enterprise Security Suite",
    "Category": "Software",
    "StockLevel": 45,
    "ReorderPoint": 20,
    "UnitCost": 299.99,
    "SupplierId": "SUP-001",
    "SupplierName": "TechCorp Solutions",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 1, 15),
    "ExpiryDate": new Date(2025, 5, 30),
    "WarehouseLocation": "A-101-B",
    "Priority": "High"
  },
  {
    "SKU": "PROD-002", 
    "ProductName": "Wireless Network Router",
    "Category": "Hardware",
    "StockLevel": 8,
    "ReorderPoint": 15,
    "UnitCost": 149.99,
    "SupplierId": "SUP-002",
    "SupplierName": "NetworkPro Inc",
    "StockStatus": "Low Stock",
    "LastOrderDate": new Date(2024, 0, 22),
    "ExpiryDate": new Date(2027, 2, 15),
    "WarehouseLocation": "B-205-A",
    "Priority": "Critical"
  },
  {
    "SKU": "PROD-003",
    "ProductName": "Cloud Storage License",
    "Category": "Service",
    "StockLevel": 120,
    "ReorderPoint": 50,
    "UnitCost": 99.99,
    "SupplierId": "SUP-003",
    "SupplierName": "CloudVault Services",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 2, 8),
    "ExpiryDate": new Date(2025, 11, 31),
    "WarehouseLocation": "Virtual-001",
    "Priority": "Medium"
  },
  {
    "SKU": "PROD-004",
    "ProductName": "Office Desk Chairs",
    "Category": "Furniture",
    "StockLevel": 0,
    "ReorderPoint": 10,
    "UnitCost": 249.99,
    "SupplierId": "SUP-004",
    "SupplierName": "ErgoFurn Ltd",
    "StockStatus": "Out of Stock",
    "LastOrderDate": new Date(2023, 11, 5),
    "ExpiryDate": new Date(2030, 5, 15),
    "WarehouseLocation": "C-310-C",
    "Priority": "Critical"
  },
  {
    "SKU": "PROD-005",
    "ProductName": "Industrial Printer Cartridges",
    "Category": "Consumables",
    "StockLevel": 35,
    "ReorderPoint": 25,
    "UnitCost": 89.99,
    "SupplierId": "SUP-005",
    "SupplierName": "PrintMax Supplies",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 2, 12),
    "ExpiryDate": new Date(2026, 8, 20),
    "WarehouseLocation": "D-115-A",
    "Priority": "Medium"
  },
  {
    "SKU": "PROD-006",
    "ProductName": "Data Backup Drives",
    "Category": "Hardware", 
    "StockLevel": 5,
    "ReorderPoint": 12,
    "UnitCost": 199.99,
    "SupplierId": "SUP-006",
    "SupplierName": "DataSafe Technologies",
    "StockStatus": "Low Stock",
    "LastOrderDate": new Date(2024, 1, 28),
    "ExpiryDate": new Date(2029, 3, 10),
    "WarehouseLocation": "A-220-B",
    "Priority": "High"
  },
  {
    "SKU": "PROD-007",
    "ProductName": "Conference Room Cameras",
    "Category": "Electronics",
    "StockLevel": 22,
    "ReorderPoint": 8,
    "UnitCost": 449.99,
    "SupplierId": "SUP-007",
    "SupplierName": "VisionTech Systems",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 2, 5),
    "ExpiryDate": new Date(2028, 1, 25),
    "WarehouseLocation": "B-305-C",
    "Priority": "Low"
  },
  {
    "SKU": "PROD-008",
    "ProductName": "Employee ID Card Stock",
    "Category": "Consumables",
    "StockLevel": 2,
    "ReorderPoint": 20,
    "UnitCost": 29.99,
    "SupplierId": "SUP-008",
    "SupplierName": "SecureCard Solutions",
    "StockStatus": "Critical Stock",
    "LastOrderDate": new Date(2023, 10, 15),
    "ExpiryDate": new Date(2025, 9, 30),
    "WarehouseLocation": "E-105-A",
    "Priority": "Critical"
  },
  {
    "SKU": "PROD-009",
    "ProductName": "Server Maintenance Tools",
    "Category": "Hardware",
    "StockLevel": 18,
    "ReorderPoint": 6,
    "UnitCost": 329.99,
    "SupplierId": "SUP-009",
    "SupplierName": "ServerPro Equipment",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 1, 18),
    "ExpiryDate": new Date(2032, 4, 12),
    "WarehouseLocation": "A-415-B",
    "Priority": "Medium"
  },
  {
    "SKU": "PROD-010",
    "ProductName": "Digital Marketing Software",
    "Category": "Software",
    "StockLevel": 75,
    "ReorderPoint": 30,
    "UnitCost": 199.99,
    "SupplierId": "SUP-010",
    "SupplierName": "MarketingPro Labs",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 2, 20),
    "ExpiryDate": new Date(2025, 7, 31),
    "WarehouseLocation": "Virtual-002",
    "Priority": "Low"
  },
  {
    "SKU": "PROD-011",
    "ProductName": "Wireless Keyboards",
    "Category": "Electronics",
    "StockLevel": 12,
    "ReorderPoint": 18,
    "UnitCost": 79.99,
    "SupplierId": "SUP-011",
    "SupplierName": "InputTech Devices",
    "StockStatus": "Low Stock",
    "LastOrderDate": new Date(2024, 0, 30),
    "ExpiryDate": new Date(2027, 6, 15),
    "WarehouseLocation": "C-205-A",
    "Priority": "High"
  },
  {
    "SKU": "PROD-012",
    "ProductName": "Fire Safety Equipment",
    "Category": "Safety",
    "StockLevel": 0,
    "ReorderPoint": 5,
    "UnitCost": 159.99,
    "SupplierId": "SUP-012",
    "SupplierName": "SafeGuard Industries",
    "StockStatus": "Out of Stock",
    "LastOrderDate": new Date(2023, 9, 12),
    "ExpiryDate": new Date(2026, 10, 20),
    "WarehouseLocation": "F-101-B",
    "Priority": "Critical"
  },
  {
    "SKU": "PROD-013",
    "ProductName": "Training Course Licenses",
    "Category": "Service",
    "StockLevel": 95,
    "ReorderPoint": 40,
    "UnitCost": 249.99,
    "SupplierId": "SUP-013",
    "SupplierName": "LearnCorp Education",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 2, 25),
    "ExpiryDate": new Date(2025, 4, 30),
    "WarehouseLocation": "Virtual-003",
    "Priority": "Medium"
  },
  {
    "SKU": "PROD-014",
    "ProductName": "Mobile Device Chargers",
    "Category": "Electronics",
    "StockLevel": 6,
    "ReorderPoint": 15,
    "UnitCost": 34.99,
    "SupplierId": "SUP-014",
    "SupplierName": "PowerTech Accessories",
    "StockStatus": "Low Stock",
    "LastOrderDate": new Date(2024, 1, 8),
    "ExpiryDate": new Date(2028, 11, 5),
    "WarehouseLocation": "D-320-C",
    "Priority": "High"
  },
  {
    "SKU": "PROD-015",
    "ProductName": "Project Management Software",
    "Category": "Software",
    "StockLevel": 50,
    "ReorderPoint": 20,
    "UnitCost": 179.99,
    "SupplierId": "SUP-015",
    "SupplierName": "ProjectFlow Solutions",
    "StockStatus": "In Stock",
    "LastOrderDate": new Date(2024, 2, 15),
    "ExpiryDate": new Date(2025, 8, 15),
    "WarehouseLocation": "Virtual-004",
    "Priority": "Low"
  }
];