
export interface LibraryBook {
  BookID: number;
  Title: string;
  Author: string;
  Genre: string;
  PublishedYear: number;
  Rating?: number;
  Language?: string;
}

export const bookCatalog: LibraryBook[] = [
  {
    "BookID": 200,
    "Title": "The Silent Patient",
    "Author": "Alex Michaelides",
    "Genre": "Thriller",
    "PublishedYear": 2017,
    "Rating": 3.6,
    "Language": "Swedish",
  },
  {
    "BookID": 201,
    "Title": "Educated",
    "Author": "Tara Westover",
    "Genre": "Fantasy",
    "PublishedYear": 2008,
    "Rating": 3.7,
    "Language": "Dutch",
  },
  {
    "BookID": 202,
    "Title": "Where the Crawdads Sing",
    "Author": "Delia Owens",
    "Genre": "Fantasy",
    "PublishedYear": 2021,
    "Rating": 4.4,
    "Language": "English",
  },
  {
    "BookID": 203,
    "Title": "Becoming",
    "Author": "Michelle Obama",
    "Genre": "Science Fiction",
    "PublishedYear": 2003,
    "Rating": 4.5,
    "Language": "English",
  },
  {
    "BookID": 204,
    "Title": "The Midnight Library",
    "Author": "Matt Haig",
    "Genre": "Historical",
    "PublishedYear": 2014,
    "Rating": 4.8,
    "Language": "German",
  },
  {
    "BookID": 205,
    "Title": "The Vanishing Half",
    "Author": "Brit Bennett",
    "Genre": "Science Fiction",
    "PublishedYear": 2017,
    "Rating": 4.2,
    "Language": "Portuguese",
  },
  {
    "BookID": 206,
    "Title": "The Four Winds",
    "Author": "Kristin Hannah",
    "Genre": "Science Fiction",
    "PublishedYear": 2013,
    "Rating": 3.6,
    "Language": "Japanese",
  },
  {
    "BookID": 207,
    "Title": "Project Hail Mary",
    "Author": "Andy Weir",
    "Genre": "Memoir",
    "PublishedYear": 2019,
    "Rating": 4.4,
    "Language": "English",
  },
  {
    "BookID": 208,
    "Title": "The Last Thing He Told Me",
    "Author": "Laura Dave",
    "Genre": "Drama",
    "PublishedYear": 2023,
    "Rating": 4.4,
    "Language": "English",
  },
  {
    "BookID": 209,
    "Title": "Verity",
    "Author": "Colleen Hoover",
    "Genre": "Self-help",
    "PublishedYear": 2016,
    "Rating": 4.1,
    "Language": "Dutch",
  },
  {
    "BookID": 210,
    "Title": "Atomic Habits",
    "Author": "James Clear",
    "Genre": "Historical",
    "PublishedYear": 2001,
    "Rating": 4.9,
    "Language": "French",
  },
  {
    "BookID": 211,
    "Title": "The Guest List",
    "Author": "Lucy Foley",
    "Genre": "Drama",
    "PublishedYear": 2021,
    "Rating": 4.5,
    "Language": "Russian",
  },
  {
    "BookID": 212,
    "Title": "The Paris Library",
    "Author": "Janet Skeslien Charles",
    "Genre": "Memoir",
    "PublishedYear": 2019,
    "Rating": 3.9,
    "Language": "Russian",
  },
  {
    "BookID": 213,
    "Title": "The Book Thief",
    "Author": "Markus Zusak",
    "Genre": "Drama",
    "PublishedYear": 2018,
    "Rating": 4.8,
    "Language": "French",
  },
  {
    "BookID": 214,
    "Title": "The Nightingale",
    "Author": "Kristin Hannah",
    "Genre": "Self-help",
    "PublishedYear": 2017,
    "Rating": 3.5,
    "Language": "Swedish",
  },
  {
    "BookID": 215,
    "Title": "Circe",
    "Author": "Madeline Miller",
    "Genre": "Thriller",
    "PublishedYear": 2017,
    "Rating": 3.6,
    "Language": "French",
  },
  {
    "BookID": 216,
    "Title": "The Song of Achilles",
    "Author": "Madeline Miller",
    "Genre": "Self-help",
    "PublishedYear": 2019,
    "Rating": 4.1,
    "Language": "English",
  },
  {
    "BookID": 217,
    "Title": "A Man Called Ove",
    "Author": "Fredrik Backman",
    "Genre": "Science Fiction",
    "PublishedYear": 2017,
    "Rating": 4.5,
    "Language": "Dutch",
  },
  {
    "BookID": 218,
    "Title": "The Alchemist",
    "Author": "Paulo Coelho",
    "Genre": "Historical",
    "PublishedYear": 2009,
    "Rating": 3.5,
    "Language": "Russian",
  },
  {
    "BookID": 219,
    "Title": "The Giver of Stars",
    "Author": "Jojo Moyes",
    "Genre": "Memoir",
    "PublishedYear": 2013,
    "Rating": 3.8,
    "Language": "Dutch",
  },
  {
    "BookID": 220,
    "Title": "The Henna Artist",
    "Author": "Alka Joshi",
    "Genre": "Historical",
    "PublishedYear": 2013,
    "Rating": 3.5,
    "Language": "Dutch",
  },
  {
    "BookID": 221,
    "Title": "The Paper Palace",
    "Author": "Miranda Cowley Heller",
    "Genre": "Mystery",
    "PublishedYear": 2013,
    "Rating": 4.3,
    "Language": "Italian",
  },
  {
    "BookID": 222,
    "Title": "Malibu Rising",
    "Author": "Taylor Jenkins Reid",
    "Genre": "Self-help",
    "PublishedYear": 2010,
    "Rating": 4.5,
    "Language": "English",
  },
  {
    "BookID": 223,
    "Title": "It Ends with Us",
    "Author": "Colleen Hoover",
    "Genre": "Romance",
    "PublishedYear": 2007,
    "Rating": 5.0,
    "Language": "Japanese",
  },
  {
    "BookID": 224,
    "Title": "Reminders of Him",
    "Author": "Colleen Hoover",
    "Genre": "Self-help",
    "PublishedYear": 2003,
    "Rating": 3.6,
    "Language": "German",
  },
  {
    "BookID": 225,
    "Title": "Ugly Love",
    "Author": "Colleen Hoover",
    "Genre": "Fantasy",
    "PublishedYear": 2006,
    "Rating": 4.2,
    "Language": "Spanish",
  },
  {
    "BookID": 226,
    "Title": "November 9",
    "Author": "Colleen Hoover",
    "Genre": "Romance",
    "PublishedYear": 2013,
    "Rating": 3.9,
    "Language": "Swedish",
  },
  {
    "BookID": 227,
    "Title": "The Seven Husbands of Evelyn Hugo",
    "Author": "Taylor Jenkins Reid",
    "Genre": "Science Fiction",
    "PublishedYear": 2020,
    "Rating": 4.9,
    "Language": "Spanish",
  },
  {
    "BookID": 228,
    "Title": "Daisy Jones & The Six",
    "Author": "Taylor Jenkins Reid",
    "Genre": "Self-help",
    "PublishedYear": 2007,
    "Rating": 4.0,
    "Language": "Portuguese",
  },
  {
    "BookID": 229,
    "Title": "The House in the Cerulean Sea",
    "Author": "TJ Klune",
    "Genre": "Drama",
    "PublishedYear": 2019,
    "Rating": 4.6,
    "Language": "English",
    }
];