export interface NutritionEntry {
  FoodID: number;
  FoodName: string;
  Protein: number;
  Fat: number;
  Carbohydrate: number;
  Fiber: number;
  Calories: number;
  Sugar: number;
  Sodium: number;
  Cholesterol: number;
  Calcium: number;
}


export const foodNutritionList : NutritionEntry[] = [
    {
        "FoodID": 1,
        "FoodName": "Chicken Salad",
        "Protein": 27,
        "Fat": 6,
        "Carbohydrate": 41,
        "Fiber": 6,
        "Calories": 199,
        "Sugar": 10,
        "Sodium": 387,
        "Cholesterol": 56,
        "Calcium": 145
    },
    {
        "FoodID": 2,
        "FoodName": "Pasta",
        "Protein": 9,
        "Fat": 13,
        "Carbohydrate": 18,
        "Fiber": 3,
        "Calories": 129,
        "Sugar": 16,
        "Sodium": 359,
        "Cholesterol": 53,
        "Calcium": 55
    },
    {
        "FoodID": 3,
        "FoodName": "Grilled Salmon",
        "Protein": 24,
        "Fat": 6,
        "Carbohydrate": 47,
        "Fiber": 12,
        "Calories": 271,
        "Sugar": 13,
        "Sodium": 447,
        "Cholesterol": 68,
        "Calcium": 223
    },
    {
        "FoodID": 4,
        "FoodName": "Veggie Burger",
        "Protein": 20,
        "Fat": 8,
        "Carbohydrate": 18,
        "Fiber": 13,
        "Calories": 117,
        "Sugar": 2,
        "Sodium": 375,
        "Cholesterol": 50,
        "Calcium": 106
    },
    {
        "FoodID": 5,
        "FoodName": "Fruit Smoothie",
        "Protein": 11,
        "Fat": 20,
        "Carbohydrate": 35,
        "Fiber": 2,
        "Calories": 321,
        "Sugar": 13,
        "Sodium": 467,
        "Cholesterol": 72,
        "Calcium": 299
    },
    {
        "FoodID": 6,
        "FoodName": "Tofu Stir Fry",
        "Protein": 8,
        "Fat": 8,
        "Carbohydrate": 47,
        "Fiber": 12,
        "Calories": 337,
        "Sugar": 7,
        "Sodium": 233,
        "Cholesterol": 30,
        "Calcium": 112
    },
    {
        "FoodID": 7,
        "FoodName": "Beef Steak",
        "Protein": 9,
        "Fat": 17,
        "Carbohydrate": 16,
        "Fiber": 8,
        "Calories": 217,
        "Sugar": 5,
        "Sodium": 56,
        "Cholesterol": 32,
        "Calcium": 235
    },
    {
        "FoodID": 8,
        "FoodName": "Quinoa Bowl",
        "Protein": 17,
        "Fat": 17,
        "Carbohydrate": 50,
        "Fiber": 5,
        "Calories": 322,
        "Sugar": 14,
        "Sodium": 359,
        "Cholesterol": 78,
        "Calcium": 87
    },
    {
        "FoodID": 9,
        "FoodName": "Turkey Sandwich",
        "Protein": 24,
        "Fat": 12,
        "Carbohydrate": 21,
        "Fiber": 5,
        "Calories": 197,
        "Sugar": 15,
        "Sodium": 491,
        "Cholesterol": 74,
        "Calcium": 243
    },
    {
        "FoodID": 10,
        "FoodName": "Lentil Soup",
        "Protein": 20,
        "Fat": 16,
        "Carbohydrate": 38,
        "Fiber": 8,
        "Calories": 160,
        "Sugar": 1,
        "Sodium": 446,
        "Cholesterol": 61,
        "Calcium": 277
    },
    {
        "FoodID": 11,
        "FoodName": "Caesar Salad",
        "Protein": 17,
        "Fat": 11,
        "Carbohydrate": 42,
        "Fiber": 15,
        "Calories": 401,
        "Sugar": 16,
        "Sodium": 379,
        "Cholesterol": 46,
        "Calcium": 197
    },
    {
        "FoodID": 12,
        "FoodName": "Rice Pilaf",
        "Protein": 23,
        "Fat": 14,
        "Carbohydrate": 20,
        "Fiber": 6,
        "Calories": 425,
        "Sugar": 19,
        "Sodium": 429,
        "Cholesterol": 57,
        "Calcium": 276
    },
    {
        "FoodID": 13,
        "FoodName": "Shrimp Tacos",
        "Protein": 20,
        "Fat": 14,
        "Carbohydrate": 43,
        "Fiber": 7,
        "Calories": 364,
        "Sugar": 13,
        "Sodium": 380,
        "Cholesterol": 48,
        "Calcium": 212
    },
    {
        "FoodID": 14,
        "FoodName": "Oatmeal",
        "Protein": 20,
        "Fat": 5,
        "Carbohydrate": 43,
        "Fiber": 4,
        "Calories": 355,
        "Sugar": 7,
        "Sodium": 358,
        "Cholesterol": 26,
        "Calcium": 271
    },
    {
        "FoodID": 15,
        "FoodName": "Greek Yogurt",
        "Protein": 5,
        "Fat": 5,
        "Carbohydrate": 15,
        "Fiber": 15,
        "Calories": 291,
        "Sugar": 14,
        "Sodium": 142,
        "Cholesterol": 21,
        "Calcium": 263
    },
    {
        "FoodID": 16,
        "FoodName": "Avocado Toast",
        "Protein": 13,
        "Fat": 8,
        "Carbohydrate": 44,
        "Fiber": 10,
        "Calories": 184,
        "Sugar": 11,
        "Sodium": 497,
        "Cholesterol": 52,
        "Calcium": 249
    },
    {
        "FoodID": 17,
        "FoodName": "Egg Omelette",
        "Protein": 11,
        "Fat": 6,
        "Carbohydrate": 10,
        "Fiber": 4,
        "Calories": 383,
        "Sugar": 17,
        "Sodium": 250,
        "Cholesterol": 56,
        "Calcium": 219
    },
    {
        "FoodID": 18,
        "FoodName": "Sweet Potato Fries",
        "Protein": 13,
        "Fat": 4,
        "Carbohydrate": 17,
        "Fiber": 6,
        "Calories": 359,
        "Sugar": 11,
        "Sodium": 155,
        "Cholesterol": 20,
        "Calcium": 142
    },
    {
        "FoodID": 19,
        "FoodName": "Broccoli Soup",
        "Protein": 15,
        "Fat": 18,
        "Carbohydrate": 43,
        "Fiber": 9,
        "Calories": 233,
        "Sugar": 3,
        "Sodium": 121,
        "Cholesterol": 29,
        "Calcium": 226
    },
    {
        "FoodID": 20,
        "FoodName": "Mushroom Risotto",
        "Protein": 16,
        "Fat": 10,
        "Carbohydrate": 22,
        "Fiber": 4,
        "Calories": 134,
        "Sugar": 4,
        "Sodium": 422,
        "Cholesterol": 57,
        "Calcium": 274
    },
    {
        "FoodID": 21,
        "FoodName": "Chickpea Curry",
        "Protein": 21,
        "Fat": 1,
        "Carbohydrate": 20,
        "Fiber": 12,
        "Calories": 458,
        "Sugar": 13,
        "Sodium": 387,
        "Cholesterol": 73,
        "Calcium": 77
    },
    {
        "FoodID": 22,
        "FoodName": "Spinach Wrap",
        "Protein": 23,
        "Fat": 4,
        "Carbohydrate": 24,
        "Fiber": 8,
        "Calories": 404,
        "Sugar": 0,
        "Sodium": 140,
        "Cholesterol": 5,
        "Calcium": 266
    },
    {
        "FoodID": 23,
        "FoodName": "Banana Pancakes",
        "Protein": 12,
        "Fat": 15,
        "Carbohydrate": 11,
        "Fiber": 15,
        "Calories": 335,
        "Sugar": 12,
        "Sodium": 366,
        "Cholesterol": 17,
        "Calcium": 177
    },
    {
        "FoodID": 24,
        "FoodName": "Zucchini Noodles",
        "Protein": 17,
        "Fat": 13,
        "Carbohydrate": 14,
        "Fiber": 1,
        "Calories": 464,
        "Sugar": 20,
        "Sodium": 424,
        "Cholesterol": 2,
        "Calcium": 69
    },
    {
        "FoodID": 25,
        "FoodName": "Tomato Soup",
        "Protein": 15,
        "Fat": 10,
        "Carbohydrate": 11,
        "Fiber": 6,
        "Calories": 229,
        "Sugar": 10,
        "Sodium": 402,
        "Cholesterol": 99,
        "Calcium": 189
    },
    {
        "FoodID": 26,
        "FoodName": "Cottage Cheese",
        "Protein": 29,
        "Fat": 18,
        "Carbohydrate": 35,
        "Fiber": 4,
        "Calories": 114,
        "Sugar": 11,
        "Sodium": 52,
        "Cholesterol": 49,
        "Calcium": 274
    },
    {
        "FoodID": 27,
        "FoodName": "Grilled Cheese",
        "Protein": 7,
        "Fat": 3,
        "Carbohydrate": 27,
        "Fiber": 11,
        "Calories": 172,
        "Sugar": 18,
        "Sodium": 492,
        "Cholesterol": 35,
        "Calcium": 92
    },
    {
        "FoodID": 28,
        "FoodName": "Peanut Butter Toast",
        "Protein": 22,
        "Fat": 10,
        "Carbohydrate": 19,
        "Fiber": 1,
        "Calories": 480,
        "Sugar": 11,
        "Sodium": 303,
        "Cholesterol": 23,
        "Calcium": 170
    },
    {
        "FoodID": 29,
        "FoodName": "Berry Parfait",
        "Protein": 29,
        "Fat": 20,
        "Carbohydrate": 14,
        "Fiber": 13,
        "Calories": 238,
        "Sugar": 13,
        "Sodium": 280,
        "Cholesterol": 24,
        "Calcium": 201
    },
    {
        "FoodID": 30,
        "FoodName": "Stuffed Peppers",
        "Protein": 7,
        "Fat": 4,
        "Carbohydrate": 43,
        "Fiber": 8,
        "Calories": 278,
        "Sugar": 8,
        "Sodium": 270,
        "Cholesterol": 46,
        "Calcium": 238
    },
    {
        "FoodID": 31,
        "FoodName": "Baked Cod",
        "Protein": 15,
        "Fat": 13,
        "Carbohydrate": 12,
        "Fiber": 5,
        "Calories": 202,
        "Sugar": 16,
        "Sodium": 441,
        "Cholesterol": 78,
        "Calcium": 289
    },
    {
        "FoodID": 32,
        "FoodName": "Veggie Pizza",
        "Protein": 12,
        "Fat": 14,
        "Carbohydrate": 29,
        "Fiber": 15,
        "Calories": 222,
        "Sugar": 16,
        "Sodium": 436,
        "Cholesterol": 10,
        "Calcium": 257
    },
    {
        "FoodID": 33,
        "FoodName": "Chicken Wrap",
        "Protein": 19,
        "Fat": 13,
        "Carbohydrate": 28,
        "Fiber": 2,
        "Calories": 218,
        "Sugar": 19,
        "Sodium": 219,
        "Cholesterol": 57,
        "Calcium": 99
    },
    {
        "FoodID": 34,
        "FoodName": "Beef Burrito",
        "Protein": 29,
        "Fat": 11,
        "Carbohydrate": 40,
        "Fiber": 9,
        "Calories": 227,
        "Sugar": 11,
        "Sodium": 168,
        "Cholesterol": 93,
        "Calcium": 143
    },
    {
        "FoodID": 35,
        "FoodName": "Tofu Burger",
        "Protein": 16,
        "Fat": 4,
        "Carbohydrate": 32,
        "Fiber": 7,
        "Calories": 343,
        "Sugar": 17,
        "Sodium": 164,
        "Cholesterol": 98,
        "Calcium": 241
    },
    {
        "FoodID": 36,
        "FoodName": "Egg Salad",
        "Protein": 20,
        "Fat": 5,
        "Carbohydrate": 23,
        "Fiber": 10,
        "Calories": 332,
        "Sugar": 7,
        "Sodium": 366,
        "Cholesterol": 59,
        "Calcium": 174
    },
    {
        "FoodID": 37,
        "FoodName": "Pumpkin Soup",
        "Protein": 25,
        "Fat": 12,
        "Carbohydrate": 12,
        "Fiber": 4,
        "Calories": 142,
        "Sugar": 4,
        "Sodium": 378,
        "Cholesterol": 23,
        "Calcium": 204
    },
    {
        "FoodID": 38,
        "FoodName": "Rice and Beans",
        "Protein": 12,
        "Fat": 16,
        "Carbohydrate": 20,
        "Fiber": 14,
        "Calories": 243,
        "Sugar": 9,
        "Sodium": 331,
        "Cholesterol": 36,
        "Calcium": 155
    },
    {
        "FoodID": 39,
        "FoodName": "Fish Curry",
        "Protein": 9,
        "Fat": 16,
        "Carbohydrate": 15,
        "Fiber": 15,
        "Calories": 375,
        "Sugar": 6,
        "Sodium": 244,
        "Cholesterol": 35,
        "Calcium": 159
    },
    {
        "FoodID": 40,
        "FoodName": "Veggie Lasagna",
        "Protein": 8,
        "Fat": 6,
        "Carbohydrate": 13,
        "Fiber": 15,
        "Calories": 300,
        "Sugar": 5,
        "Sodium": 217,
        "Cholesterol": 48,
        "Calcium": 83
    },
    {
        "FoodID": 41,
        "FoodName": "Ham Sandwich",
        "Protein": 13,
        "Fat": 6,
        "Carbohydrate": 35,
        "Fiber": 4,
        "Calories": 171,
        "Sugar": 12,
        "Sodium": 89,
        "Cholesterol": 80,
        "Calcium": 228
    },
    {
        "FoodID": 42,
        "FoodName": "Cucumber Salad",
        "Protein": 11,
        "Fat": 10,
        "Carbohydrate": 17,
        "Fiber": 6,
        "Calories": 388,
        "Sugar": 17,
        "Sodium": 148,
        "Cholesterol": 100,
        "Calcium": 53
    },
    {
        "FoodID": 43,
        "FoodName": "Apple Pie",
        "Protein": 23,
        "Fat": 19,
        "Carbohydrate": 27,
        "Fiber": 3,
        "Calories": 127,
        "Sugar": 13,
        "Sodium": 330,
        "Cholesterol": 1,
        "Calcium": 53
    },
    {
        "FoodID": 44,
        "FoodName": "Carrot Cake",
        "Protein": 6,
        "Fat": 15,
        "Carbohydrate": 12,
        "Fiber": 6,
        "Calories": 498,
        "Sugar": 12,
        "Sodium": 182,
        "Cholesterol": 78,
        "Calcium": 293
    },
    {
        "FoodID": 45,
        "FoodName": "Green Smoothie",
        "Protein": 16,
        "Fat": 11,
        "Carbohydrate": 37,
        "Fiber": 11,
        "Calories": 425,
        "Sugar": 6,
        "Sodium": 368,
        "Cholesterol": 22,
        "Calcium": 91
    },
    {
        "FoodID": 46,
        "FoodName": "Protein Bar",
        "Protein": 8,
        "Fat": 15,
        "Carbohydrate": 22,
        "Fiber": 14,
        "Calories": 499,
        "Sugar": 19,
        "Sodium": 332,
        "Cholesterol": 61,
        "Calcium": 222
    },
    {
        "FoodID": 47,
        "FoodName": "Trail Mix",
        "Protein": 9,
        "Fat": 10,
        "Carbohydrate": 35,
        "Fiber": 14,
        "Calories": 423,
        "Sugar": 20,
        "Sodium": 416,
        "Cholesterol": 72,
        "Calcium": 220
    },
    {
        "FoodID": 48,
        "FoodName": "Granola Bowl",
        "Protein": 22,
        "Fat": 1,
        "Carbohydrate": 46,
        "Fiber": 7,
        "Calories": 312,
        "Sugar": 13,
        "Sodium": 441,
        "Cholesterol": 9,
        "Calcium": 58
    },
    {
        "FoodID": 49,
        "FoodName": "Mixed Nuts",
        "Protein": 6,
        "Fat": 6,
        "Carbohydrate": 45,
        "Fiber": 4,
        "Calories": 464,
        "Sugar": 2,
        "Sodium": 370,
        "Cholesterol": 51,
        "Calcium": 195
    },
    {
        "FoodID": 50,
        "FoodName": "Hummus Plate",
        "Protein": 18,
        "Fat": 10,
        "Carbohydrate": 34,
        "Fiber": 3,
        "Calories": 412,
        "Sugar": 9,
        "Sodium": 467,
        "Cholesterol": 66,
        "Calcium": 119
    }
]