export const orderDatas: object[] = [
  {
    OrderID: 10248,
    CustomerID: "VINET",
    EmployeeID: 5,
    OrderDate: new Date(1996, 6, 4),
    RequiredDate: new Date(1996, 7, 1),
    ShippedDate: new Date(1996, 6, 16),
    OrderStatus: "Order Placed",
    ShipVia: 3,
    Freight: 32.38,
    ShipName: "Vins et alcools Chevalier",
    ShipAddress: "59 rue de l'Abbaye",
    ShipCity: "Reims",
    ShipRegion: null,
    ShipPostalCode: "51100",
    ShipCountry: "France",
    Quantity: 1,
  },
  {
    OrderID: 10249,
    CustomerID: "TOMSP",
    EmployeeID: 6,
    OrderDate: new Date(1996, 6, 5),
    RequiredDate: new Date(1996, 7, 16),
    ShippedDate: new Date(1996, 6, 10),
    ShipVia: 1,
    Freight: 11.61,
    ShipName: "Toms Spezialit\u00e4ten",
    ShipAddress: "Luisenstr. 48",
    ShipCity: "M\u00fcnster",
    ShipRegion: null,
    ShipPostalCode: "44087",
    ShipCountry: "Germany",
    OrderStatus: "Processing",
    Quantity: 3,
  },
  {
    OrderID: 10250,
    CustomerID: "HANAR",
    EmployeeID: 4,
    OrderDate: new Date(1996, 6, 8),
    RequiredDate: new Date(1996, 7, 5),
    ShippedDate: new Date(1996, 6, 12),
    ShipVia: 2,
    Freight: 65.83,
    ShipName: "Hanari Carnes",
    ShipAddress: "Rua do Pa\u00e7o, 67",
    ShipCity: "Rio de Janeiro",
    ShipRegion: "RJ",
    ShipPostalCode: "05454-876",
    ShipCountry: "Brazil",
    OrderStatus: "Order Placed",
    Quantity: 5,
  },
  {
    OrderID: 10251,
    CustomerID: "VICTE",
    EmployeeID: 3,
    OrderDate: new Date(1996, 6, 8),
    RequiredDate: new Date(1996, 7, 5),
    ShippedDate: new Date(1996, 6, 15),
    ShipVia: 1,
    Freight: 41.34,
    ShipName: "Victuailles en stock",
    ShipAddress: "2, rue du Commerce",
    ShipCity: "Lyon",
    ShipRegion: null,
    ShipPostalCode: "69004",
    ShipCountry: "France",
    OrderStatus: "Order Placed",
    Quantity: 6,
  },
  {
    OrderID: 10252,
    CustomerID: "SUPRD",
    EmployeeID: 4,
    OrderDate: new Date(1996, 6, 9),
    RequiredDate: new Date(1996, 7, 6),
    ShippedDate: new Date(1996, 6, 11),
    ShipVia: 2,
    Freight: 51.3,
    ShipName: "Supr\u00eames d\u00e9lices",
    ShipAddress: "Boulevard Tirou, 255",
    ShipCity: "Charleroi",
    ShipRegion: null,
    ShipPostalCode: "B-6000",
    ShipCountry: "Belgium",
    OrderStatus: "Processing",
    Quantity: 5,
  },
  {
    OrderID: 10253,
    CustomerID: "HANAR",
    EmployeeID: 3,
    OrderDate: new Date(1996, 6, 10),
    RequiredDate: new Date(1996, 6, 24),
    ShippedDate: new Date(1996, 6, 16),
    ShipVia: 2,
    Freight: 58.17,
    ShipName: "Hanari Carnes",
    ShipAddress: "Rua do Pa\u00e7o, 67",
    ShipCity: "Rio de Janeiro",
    ShipRegion: "RJ",
    ShipPostalCode: "05454-876",
    ShipCountry: "Brazil",
    OrderStatus: "Processing",
    Quantity: 7,
  },
  {
    OrderID: 10254,
    CustomerID: "CHOPS",
    EmployeeID: 5,
    OrderDate: new Date(1996, 6, 11),
    RequiredDate: new Date(1996, 7, 8),
    ShippedDate: new Date(1996, 6, 23),
    ShipVia: 2,
    Freight: 22.98,
    ShipName: "Chop-suey Chinese",
    ShipAddress: "Hauptstr. 31",
    ShipCity: "Bern",
    ShipRegion: null,
    ShipPostalCode: "3012",
    ShipCountry: "Switzerland",
    OrderStatus: "Order Placed",
    Quantity: 8,
  },
  {
    OrderID: 10255,
    CustomerID: "RICSU",
    EmployeeID: 9,
    OrderDate: new Date(1996, 6, 12),
    RequiredDate: new Date(1996, 7, 9),
    ShippedDate: new Date(1996, 6, 15),
    ShipVia: 3,
    Freight: 148.33,
    ShipName: "Richter Supermarkt",
    ShipAddress: "Starenweg 5",
    ShipCity: "Gen\u00e8ve",
    ShipRegion: null,
    ShipPostalCode: "1204",
    ShipCountry: "Switzerland",
    OrderStatus: "Processing",
    Quantity: 8,
  },
  {
    OrderID: 10256,
    CustomerID: "WELLI",
    EmployeeID: 3,
    OrderDate: new Date(1996, 6, 15),
    RequiredDate: new Date(1996, 7, 12),
    ShippedDate: new Date(1996, 6, 17),
    ShipVia: 2,
    Freight: 13.97,
    ShipName: "Wellington Importadora",
    ShipAddress: "Rua do Mercado, 12",
    ShipCity: "Resende",
    ShipRegion: "SP",
    ShipPostalCode: "08737-363",
    ShipCountry: "Brazil",
    OrderStatus: "Order Placed",
    Quantity: 1,
  },
  {
    OrderID: 10257,
    CustomerID: "HILAA",
    EmployeeID: 4,
    OrderDate: new Date(1996, 6, 16),
    RequiredDate: new Date(1996, 7, 13),
    ShippedDate: new Date(1996, 6, 22),
    ShipVia: 3,
    Freight: 81.91,
    ShipName: "HILARION-Abastos",
    ShipAddress: "Carrera 22 con Ave. Carlos Soublette #8-35",
    ShipCity: "San Crist\u00f3bal",
    ShipRegion: "T\u00e1chira",
    ShipPostalCode: "5022",
    ShipCountry: "Venezuela",
    OrderStatus: "Processing",
    Quantity: 1,
  },
  {
    OrderID: 10258,
    CustomerID: "ERNSH",
    EmployeeID: 1,
    OrderDate: new Date(1996, 6, 17),
    RequiredDate: new Date(1996, 7, 14),
    ShippedDate: new Date(1996, 6, 23),
    ShipVia: 1,
    Freight: 140.51,
    ShipName: "Ernst Handel",
    ShipAddress: "Kirchgasse 6",
    ShipCity: "Graz",
    ShipRegion: null,
    ShipPostalCode: "8010",
    ShipCountry: "Austria",
    OrderStatus: "Order Placed",
    Quantity: 1,
  },
  {
    OrderID: 10259,
    CustomerID: "CENTC",
    EmployeeID: 4,
    OrderDate: new Date(1996, 6, 18),
    RequiredDate: new Date(1996, 7, 15),
    ShippedDate: new Date(1996, 6, 25),
    ShipVia: 3,
    Freight: 3.25,
    ShipName: "Centro comercial Moctezuma",
    ShipAddress: "Sierras de Granada 9993",
    ShipCity: "M\u00e9xico D.F.",
    ShipRegion: null,
    ShipPostalCode: "05022",
    ShipCountry: "Mexico",
    OrderStatus: "Processing",
    Quantity: 1,
  },
  {
    OrderID: 10260,
    CustomerID: "OTTIK",
    EmployeeID: 4,
    OrderDate: new Date(1996, 6, 19),
    RequiredDate: new Date(1996, 7, 16),
    ShippedDate: new Date(1996, 6, 29),
    ShipVia: 1,
    Freight: 55.09,
    ShipName: "Ottilies K\u00e4seladen",
    ShipAddress: "Mehrheimerstr. 369",
    ShipCity: "K\u00f6ln",
    ShipRegion: null,
    ShipPostalCode: "50739",
    ShipCountry: "Germany",
    OrderStatus: "Order Placed",
    Quantity: 1,
  },
  {
    OrderID: 10261,
    CustomerID: "QUEDE",
    EmployeeID: 4,
    OrderDate: new Date(1996, 6, 19),
    RequiredDate: new Date(1996, 7, 16),
    ShippedDate: new Date(1996, 6, 30),
    ShipVia: 2,
    Freight: 3.05,
    ShipName: "Que Del\u00edcia",
    ShipAddress: "Rua da Panificadora, 12",
    ShipCity: "Rio de Janeiro",
    ShipRegion: "RJ",
    ShipPostalCode: "02389-673",
    ShipCountry: "Brazil",
    OrderStatus: "Processing",
    Quantity: 1,
  },
  {
    OrderID: 10262,
    CustomerID: "RATTC",
    EmployeeID: 8,
    OrderDate: new Date(1996, 6, 22),
    RequiredDate: new Date(1996, 7, 19),
    ShippedDate: new Date(1996, 6, 25),
    ShipVia: 3,
    Freight: 48.29,
    ShipName: "Rattlesnake Canyon Grocery",
    ShipAddress: "2817 Milton Dr.",
    ShipCity: "Albuquerque",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    OrderStatus: "Order Placed",
    Quantity: 1,
  },
];