export const orderData: object[] = [
    {
        'OrderID': 10248,
        'CustomerID': 'ID-VINET',
        'CustomerName': 'Maria ',
        'OrderDate': new Date(2024, 4, 4),
        'ShippedDate': new Date(2024, 4, 16),
        'Freight': 32.38,
        'ShipName': 'Vins et alcools Chevalier',
        'ShipAddress': '59 rue de l Abbaye',
        'ShipCity': 'Reims',
        'ShipRegion': null,
        'ShipCountry': 'France',
        'EmployeeID': 3,
        'Verified': true
    },
    {
        'OrderID': 10249,
        'CustomerID': 'ID-TOMSP',
        'CustomerName': 'Ana Trujillo',
        'OrderDate': new Date(2024, 4, 5),
        'ShippedDate': new Date(2024, 4, 10),
        'Freight': 11.61,
        'ShipName': 'Toms Spezialitaten',
        'ShipAddress': 'Luisenstr. 48',
        'ShipCity': 'Munster',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 5,
        'Verified': false
    },
    {
        'OrderID': 10250,
        'CustomerID': 'ID-HANAR',
        'CustomerName': 'Antonio Moreno',
        'OrderDate': new Date(2024, 4, 8),
        'ShippedDate': new Date(2024, 4, 12),
        'Freight': 65.83,
        'ShipName': 'Hanari Carnes',
        'ShipAddress': 'Rua do Paco, 67',
        'ShipCity': 'Rio de Janeiro',
        'ShipRegion': 'RJ',
        'ShipCountry': 'Brazil',
        'EmployeeID': 1,
        'Verified': false
    },
    {
        'OrderID': 10251,
        'CustomerID': 'ID-VICTE',
        'CustomerName': 'Thomas Hardy',
        'OrderDate': new Date(2024, 4, 8),
        'ShippedDate': new Date(2024, 4, 15),
        'Freight': 41.34,
        'ShipName': 'Victuailles en stock',
        'ShipAddress': '2, rue du Commerce',
        'ShipCity': 'Lyon',
        'ShipRegion': null,
        'ShipCountry': 'France',
        'EmployeeID': 6,
        'Verified': true
    },
    {
        'OrderID': 10252,
        'CustomerID': 'ID-SUPRD',
        'CustomerName': 'Christina Berglund',
        'OrderDate': new Date(2024, 4, 9),
        'ShippedDate': new Date(2024, 4, 11),
        'Freight': 51.3,
        'ShipName': 'Supremes delices',
        'ShipAddress': 'Boulevard Tirou, 255',
        'ShipCity': 'Charleroi',
        'ShipRegion': null,
        'ShipCountry': 'Belgium',
        'EmployeeID': 2,
        'Verified': false
    },
    {
        'OrderID': 10253,
        'CustomerID': 'ID-HANAR',
        'CustomerName': 'Hanna Moos',
        'OrderDate': new Date(2024, 4, 10),
        'ShippedDate': new Date(2024, 4, 16),
        'Freight': 58.17,
        'ShipName': 'Hanari Carnes',
        'ShipAddress': 'Rua do Paco, 67',
        'ShipCity': 'Rio de Janeiro',
        'ShipRegion': 'RJ',
        'ShipCountry': 'Brazil',
        'EmployeeID': 4,
        'Verified': true
    },
    {
        'OrderID': 10254,
        'CustomerID': 'ID-CHOPS',
        'CustomerName': 'Frederique Citeaux',
        'OrderDate': new Date(2024, 4, 11),
        'ShippedDate': new Date(2024, 4, 23),
        'Freight': 22.98,
        'ShipName': 'Chop-suey Chinese',
        'ShipAddress': 'Hauptstr. 31',
        'ShipCity': 'Bern',
        'ShipRegion': null,
        'ShipCountry': 'Switzerland',
        'EmployeeID': 9,
        'Verified': false
    },
    {
        'OrderID': 10255,
        'CustomerID': 'ID-RICSU',
        'CustomerName': 'Martin Sommer',
        'OrderDate': new Date(2024, 4, 12),
        'ShippedDate': new Date(2024, 4, 15),
        'Freight': 148.33,
        'ShipName': 'Richter Supermarkt',
        'ShipAddress': 'Starenweg 5',
        'ShipCity': 'Geneve',
        'ShipRegion': null,
        'ShipCountry': 'Switzerland',
        'EmployeeID': 7,
        'Verified': true
    },
    {
        'OrderID': 10256,
        'CustomerID': 'ID-WELLI',
        'CustomerName': 'Laurence Lebihan',
        'OrderDate': new Date(2024, 4, 15),
        'ShippedDate': new Date(2024, 4, 17),
        'Freight': 13.97,
        'ShipName': 'Wellington Importadora',
        'ShipAddress': 'Rua do Mercado, 12',
        'ShipCity': 'Resende',
        'ShipRegion': 'SP',
        'ShipCountry': 'Brazil',
        'EmployeeID': 8,
        'Verified': true
    },
    {
        'OrderID': 10257,
        'CustomerID': 'ID-HILAA',
        'CustomerName': 'Elizabeth Lincoln',
        'OrderDate': new Date(2024, 4, 16),
        'ShippedDate': new Date(2024, 4, 22),
        'Freight': 81.91,
        'ShipName': 'HILARION-Abastos',
        'ShipAddress': 'Carrera 22 con Ave. Carlos Soublette #8-35',
        'ShipCity': 'San Cristobal',
        'ShipRegion': 'Tachira',
        'ShipCountry': 'Venezuela',
        'EmployeeID': 5,
        'Verified': false
    },
    {
        'OrderID': 10258,
        'CustomerID': 'ID-ERNSH',
        'CustomerName': 'Victoria Ashworth',
        'OrderDate': new Date(2024, 4, 17),
        'ShippedDate': new Date(2024, 4, 23),
        'Freight': 140.51,
        'ShipName': 'Ernst Handel',
        'ShipAddress': 'Kirchgasse 6',
        'ShipCity': 'Graz',
        'ShipRegion': null,
        'ShipCountry': 'Austria',
        'EmployeeID': 1,
        'Verified': true
    },
    {
        'OrderID': 10259,
        'CustomerID': 'ID-CENTC',
        'CustomerName': 'Patricio Simpson',
        'OrderDate': new Date(2024, 4, 18),
        'ShippedDate': new Date(2024, 4, 25),
        'Freight': 3.25,
        'ShipName': 'Centro comercial Moctezuma',
        'ShipAddress': 'Sierras de Granada 9993',
        'ShipCity': 'Mexico D.F.',
        'ShipRegion': null,
        'ShipCountry': 'Mexico',
        'EmployeeID': 6,
        'Verified': false
    },
    {
        'OrderID': 10260,
        'CustomerID': 'ID-OTTIK',
        'CustomerName': 'Francisco Chang',
        'OrderDate': new Date(2024, 4, 19),
        'ShippedDate': new Date(2024, 4, 29),
        'Freight': 55.09,
        'ShipName': 'Ottilies Kaseladen',
        'ShipAddress': 'Mehrheimerstr. 369',
        'ShipCity': 'Koln',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 2,
        'Verified': true
    },
    {
        'OrderID': 10261,
        'CustomerID': 'ID-QUEDE',
        'CustomerName': 'Yang Wang',
        'OrderDate': new Date(2024, 4, 19),
        'ShippedDate': new Date(2024, 4, 30),
        'Freight': 3.05,
        'ShipName': 'Que Delicia',
        'ShipAddress': 'Rua da Panificadora, 12',
        'ShipCity': 'Rio de Janeiro',
        'ShipRegion': 'RJ',
        'ShipCountry': 'Brazil',
        'EmployeeID': 7,
        'Verified': false
    },
    {
        'OrderID': 10262,
        'CustomerID': 'ID-RATTC',
        'CustomerName': 'Pedro Afonso',
        'OrderDate': new Date(2024, 4, 22),
        'ShippedDate': new Date(2024, 4, 25),
        'Freight': 48.29,
        'ShipName': 'Rattlesnake Canyon Grocery',
        'ShipAddress': '2817 Milton Dr.',
        'ShipCity': 'Albuquerque',
        'ShipRegion': 'NM',
        'ShipCountry': 'USA',
        'EmployeeID': 4,
        'Verified': true
    },
    {
        'OrderID': 10263,
        'CustomerID': 'ID-ERNSH',
        'CustomerName': 'Elizabeth Brown',
        'OrderDate': new Date(2024, 4, 23),
        'ShippedDate': new Date(2024, 4, 31),
        'Freight': 146.06,
        'ShipName': 'Ernst Handel',
        'ShipAddress': 'Kirchgasse 6',
        'ShipCity': 'Graz',
        'ShipRegion': null,
        'ShipCountry': 'Austria',
        'EmployeeID': 3,
        'Verified': false
    },
    {
        'OrderID': 10264,
        'CustomerID': 'ID-FOLKO',
        'CustomerName': 'Sven Ottlieb',
        'OrderDate': new Date(2024, 4, 24),
        'ShippedDate': new Date(2024, 5, 23),
        'Freight': 3.67,
        'ShipName': 'Folk och fa HB',
        'ShipAddress': 'Akergatan 24',
        'ShipCity': 'Bracke',
        'ShipRegion': null,
        'ShipCountry': 'Sweden',
        'EmployeeID': 8,
        'Verified': true
    },
    {
        'OrderID': 10265,
        'CustomerID': 'ID-BLONP',
        'CustomerName': 'Ann Devon',
        'OrderDate': new Date(2024, 4, 25),
        'ShippedDate': new Date(2024, 5, 12),
        'Freight': 55.28,
        'ShipName': 'Blondel pere et fils',
        'ShipAddress': '24, place Kleber',
        'ShipCity': 'Strasbourg',
        'ShipRegion': null,
        'ShipCountry': 'France',
        'EmployeeID': 3,
        'Verified': false
    },
    {
        'OrderID': 10266,
        'CustomerID': 'ID-WARTH',
        'CustomerName': 'Roland Mendel',
        'OrderDate': new Date(2024, 4, 26),
        'ShippedDate': new Date(2024, 4, 31),
        'Freight': 25.73,
        'ShipName': 'Wartian Herkku',
        'ShipAddress': 'Torikatu 38',
        'ShipCity': 'Oulu',
        'ShipRegion': null,
        'ShipCountry': 'Finland',
        'EmployeeID': 2,
        'Verified': false
    },
    {
        'OrderID': 10267,
        'CustomerID': 'ID-FRANK',
        'CustomerName': 'Aria Cruz',
        'OrderDate': new Date(2024, 4, 29),
        'ShippedDate': new Date(2024, 5, 6),
        'Freight': 208.58,
        'ShipName': 'Frankenversand',
        'ShipAddress': 'Berliner Platz 43',
        'ShipCity': 'Munchen',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 4,
        'Verified': false
    },
    {
        'OrderID': 10268,
        'CustomerID': 'ID-GROSR',
        'CustomerName': 'Diego Roel',
        'OrderDate': new Date(2024, 4, 30),
        'ShippedDate': new Date(2024, 5, 2),
        'Freight': 66.29,
        'ShipName': 'GROSELLA-Restaurante',
        'ShipAddress': '5a Ave. Los Palos Grandes',
        'ShipCity': 'Caracas',
        'ShipRegion': 'DF',
        'ShipCountry': 'Venezuela',
        'EmployeeID': 2,
        'Verified': false
    },
    {
        'OrderID': 10269,
        'CustomerID': 'ID-WHITC',
        'CustomerName': 'Martine Rance',
        'OrderDate': new Date(2024, 4, 31),
        'ShippedDate': new Date(2024, 5, 9),
        'Freight': 4.56,
        'ShipName': 'White Clover Markets',
        'ShipAddress': '1029 - 12th Ave. S.',
        'ShipCity': 'Seattle',
        'ShipRegion': 'WA',
        'ShipCountry': 'USA',
        'EmployeeID': 1,
        'Verified': false
    },
    {
        'OrderID': 10270,
        'CustomerID': 'ID-WARTH',
        'CustomerName': 'Maria Larsson',
        'OrderDate': new Date(2024, 5, 1),
        'ShippedDate': new Date(2024, 5, 2),
        'Freight': 136.54,
        'ShipName': 'Wartian Herkku',
        'ShipAddress': 'Torikatu 38',
        'ShipCity': 'Oulu',
        'ShipRegion': null,
        'ShipCountry': 'Finland',
        'EmployeeID': 4,
        'Verified': false
    },
    {
        'OrderID': 10271,
        'CustomerID': 'ID-SPLIR',
        'CustomerName': 'Peter Franken',
        'OrderDate': new Date(2024, 5, 1),
        'ShippedDate': new Date(2024, 5, 30),
        'Freight': 4.54,
        'ShipName': 'Split Rail Beer & Ale',
        'ShipAddress': 'P.O. Box 555',
        'ShipCity': 'Lander',
        'ShipRegion': 'WY',
        'ShipCountry': 'USA',
        'EmployeeID': 5,
        'Verified': false
    },
    {
        'OrderID': 10272,
        'CustomerID': 'ID-RATTC',
        'CustomerName': 'Carine Schmitt',
        'OrderDate': new Date(2024, 5, 2),
        'ShippedDate': new Date(2024, 5, 6),
        'Freight': 98.03,
        'ShipName': 'Rattlesnake Canyon Grocery',
        'ShipAddress': '2817 Milton Dr.',
        'ShipCity': 'Albuquerque',
        'ShipRegion': 'NM',
        'ShipCountry': 'USA',
        'EmployeeID': 3,
        'Verified': false
    },
    {
        'OrderID': 10273,
        'CustomerID': 'ID-QUICK',
        'CustomerName': 'Paolo Accorti',
        'OrderDate': new Date(2024, 5, 5),
        'ShippedDate': new Date(2024, 5, 12),
        'Freight': 76.07,
        'ShipName': 'QUICK-Stop',
        'ShipAddress': 'Taucherstrasse 10',
        'ShipCity': 'Cunewalde',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 6,
        'Verified': false
    },
    {
        'OrderID': 10274,
        'CustomerID': 'ID-VINET',
        'CustomerName': 'Lino Rodriguez',
        'OrderDate': new Date(2024, 5, 6),
        'ShippedDate': new Date(2024, 5, 16),
        'Freight': 6.01,
        'ShipName': 'Vins et alcools Chevalier',
        'ShipAddress': '59 rue de l Abbaye',
        'ShipCity': 'Reims',
        'ShipRegion': null,
        'ShipCountry': 'France',
        'EmployeeID': 1,
        'Verified': false
    },
    {
        'OrderID': 10275,
        'CustomerID': 'ID-MAGAA',
        'CustomerName': 'Eduardo Saavedra',
        'OrderDate': new Date(2024, 5, 7),
        'ShippedDate': new Date(2024, 5, 9),
        'Freight': 26.93,
        'ShipName': 'Magazzini Alimentari Riuniti',
        'ShipAddress': 'Via Ludovico il Moro 22',
        'ShipCity': 'Bergamo',
        'ShipRegion': null,
        'ShipCountry': 'Italy',
        'EmployeeID': 3,
        'Verified': false
    },
    {
        'OrderID': 10276,
        'CustomerID': 'ID-TORTU',
        'CustomerName': 'Jose Pedro Freyre',
        'OrderDate': new Date(2024, 5, 8),
        'ShippedDate': new Date(2024, 5, 14),
        'Freight': 13.84,
        'ShipName': 'Tortuga Restaurante',
        'ShipAddress': 'Avda. Azteca 123',
        'ShipCity': 'Mexico D.F.',
        'ShipRegion': null,
        'ShipCountry': 'Mexico',
        'EmployeeID': 5,
        'Verified': true
    },
    {
        'OrderID': 10277,
        'CustomerID': 'ID-MORGK',
        'CustomerName': 'Andre Fonseca',
        'OrderDate': new Date(2024, 5, 9),
        'ShippedDate': new Date(2024, 5, 13),
        'Freight': 125.77,
        'ShipName': 'Morgenstern Gesundkost',
        'ShipAddress': 'Heerstr. 22',
        'ShipCity': 'Leipzig',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 7,
        'Verified': true
    },
    {
        'OrderID': 10278,
        'CustomerID': 'ID-BERGS',
        'CustomerName': 'Howard Snyder',
        'OrderDate': new Date(2024, 5, 12),
        'ShippedDate': new Date(2024, 5, 16),
        'Freight': 92.69,
        'ShipName': 'Berglunds snabbkop',
        'ShipAddress': 'Berguvsvagen 8',
        'ShipCity': 'Lulea',
        'ShipRegion': null,
        'ShipCountry': 'Sweden',
        'EmployeeID': 9,
        'Verified': true
    },
    {
        'OrderID': 10279,
        'CustomerID': 'ID-LEHMS',
        'CustomerName': 'Manuel Pereira',
        'OrderDate': new Date(2024, 5, 13),
        'ShippedDate': new Date(2024, 5, 16),
        'Freight': 25.83,
        'ShipName': 'Lehmanns Marktstand',
        'ShipAddress': 'Magazinweg 7',
        'ShipCity': 'Frankfurt a.M.',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 2,
        'Verified': false
    },
    {
        'OrderID': 10280,
        'CustomerID': 'ID-BERGS',
        'CustomerName': 'Mario Pontes',
        'OrderDate': new Date(2024, 5, 14),
        'ShippedDate': new Date(2024, 6, 12),
        'Freight': 8.98,
        'ShipName': 'Berglunds snabbkop',
        'ShipAddress': 'Berguvsvagen 8',
        'ShipCity': 'Lulea',
        'ShipRegion': null,
        'ShipCountry': 'Sweden',
        'EmployeeID': 4,
        'Verified': true
    },
    {
        'OrderID': 10281,
        'CustomerID': 'ID-ROMEY',
        'CustomerName': 'Carlos Hernandez',
        'OrderDate': new Date(2024, 5, 14),
        'ShippedDate': new Date(2024, 5, 21),
        'Freight': 2.94,
        'ShipName': 'Romero y tomillo',
        'ShipAddress': 'Gran Via, 1',
        'ShipCity': 'Madrid',
        'ShipRegion': null,
        'ShipCountry': 'Spain',
        'EmployeeID': 6,
        'Verified': true
    },
    {
        'OrderID': 10282,
        'CustomerID': 'ID-ROMEY',
        'CustomerName': 'Yoshi Latimer',
        'OrderDate': new Date(2024, 5, 15),
        'ShippedDate': new Date(2024, 5, 21),
        'Freight': 12.69,
        'ShipName': 'Romero y tomillo',
        'ShipAddress': 'Gran Via, 1',
        'ShipCity': 'Madrid',
        'ShipRegion': null,
        'ShipCountry': 'Spain',
        'EmployeeID': 8,
        'Verified': true
    },
    {
        'OrderID': 10283,
        'CustomerID': 'ID-LILAS',
        'CustomerName': 'Patricia McKenna',
        'OrderDate': new Date(2024, 5, 16),
        'ShippedDate': new Date(2024, 5, 23),
        'Freight': 84.81,
        'ShipName': 'LILA-Supermercado',
        'ShipAddress': 'Carrera 52 con Ave. Bolivar #65-98 Llano Largo',
        'ShipCity': 'Barquisimeto',
        'ShipRegion': 'Lara',
        'ShipCountry': 'Venezuela',
        'EmployeeID': 9,
        'Verified': true
    },
    {
        'OrderID': 10284,
        'CustomerID': 'ID-LEHMS',
        'CustomerName': 'Helen Bennett',
        'OrderDate': new Date(2024, 5, 19),
        'ShippedDate': new Date(2024, 5, 27),
        'Freight': 76.56,
        'ShipName': 'Lehmanns Marktstand',
        'ShipAddress': 'Magazinweg 7',
        'ShipCity': 'Frankfurt a.M.',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 6,
        'Verified': true
    },
    {
        'OrderID': 10285,
        'CustomerID': 'ID-QUICK',
        'CustomerName': 'Philip Cramer',
        'OrderDate': new Date(2024, 5, 20),
        'ShippedDate': new Date(2024, 5, 26),
        'Freight': 76.83,
        'ShipName': 'QUICK-Stop',
        'ShipAddress': 'Taucherstrasse 10',
        'ShipCity': 'Cunewalde',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 3,
        'Verified': true
    },
    {
        'OrderID': 10286,
        'CustomerID': 'ID-QUICK',
        'CustomerName': 'Daniel Tonini',
        'OrderDate': new Date(2024, 5, 21),
        'ShippedDate': new Date(2024, 5, 30),
        'Freight': 229.24,
        'ShipName': 'QUICK-Stop',
        'ShipAddress': 'Taucherstrasse 10',
        'ShipCity': 'Cunewalde',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 1,
        'Verified': true
    },
    {
        'OrderID': 10287,
        'CustomerID': 'ID-RICAR',
        'CustomerName': 'Annette Roulet',
        'OrderDate': new Date(2024, 5, 22),
        'ShippedDate': new Date(2024, 5, 28),
        'Freight': 12.76,
        'ShipName': 'Ricardo Adocicados',
        'ShipAddress': 'Av. Copacabana, 267',
        'ShipCity': 'Rio de Janeiro',
        'ShipRegion': 'RJ',
        'ShipCountry': 'Brazil',
        'EmployeeID': 8,
        'Verified': true
    },
    {
        'OrderID': 10288,
        'CustomerID': 'ID-REGGC',
        'CustomerName': 'Yoshi Tannamuri',
        'OrderDate': new Date(2024, 5, 23),
        'ShippedDate': new Date(2024, 6, 3),
        'Freight': 7.45,
        'ShipName': 'Reggiani Caseifici',
        'ShipAddress': 'Strada Provinciale 124',
        'ShipCity': 'Reggio Emilia',
        'ShipRegion': null,
        'ShipCountry': 'Italy',
        'EmployeeID': 4,
        'Verified': false
    },
    {
        'OrderID': 10289,
        'CustomerID': 'ID-BSBEV',
        'CustomerName': 'John Steel',
        'OrderDate': new Date(2024, 5, 26),
        'ShippedDate': new Date(2024, 5, 28),
        'Freight': 22.77,
        'ShipName': 'B s Beverages',
        'ShipAddress': 'Fauntleroy Circus',
        'ShipCity': 'London',
        'ShipRegion': null,
        'ShipCountry': 'UK',
        'EmployeeID': 2,
        'Verified': false
    },
    {
        'OrderID': 10290,
        'CustomerID': 'ID-COMMI',
        'CustomerName': 'Renate Messner',
        'OrderDate': new Date(2024, 5, 27),
        'ShippedDate': new Date(2024, 6, 3),
        'Freight': 79.7,
        'ShipName': 'Comercio Mineiro',
        'ShipAddress': 'Av. dos Lusiadas, 23',
        'ShipCity': 'Sao Paulo',
        'ShipRegion': 'SP',
        'ShipCountry': 'Brazil',
        'EmployeeID': 5,
        'Verified': false
    },
    {
        'OrderID': 10291,
        'CustomerID': 'ID-QUEDE',
        'CustomerName': 'Jaime Yorres',
        'OrderDate': new Date(2024, 5, 27),
        'ShippedDate': new Date(2024, 6, 4),
        'Freight': 6.4,
        'ShipName': 'Que Delicia',
        'ShipAddress': 'Rua da Panificadora, 12',
        'ShipCity': 'Rio de Janeiro',
        'ShipRegion': 'RJ',
        'ShipCountry': 'Brazil',
        'EmployeeID': 7,
        'Verified': false
    },
    {
        'OrderID': 10292,
        'CustomerID': 'ID-TRADH',
        'CustomerName': 'Carlos Gonzalez',
        'OrderDate': new Date(2024, 5, 28),
        'ShippedDate': new Date(2024, 6, 2),
        'Freight': 1.35,
        'ShipName': 'Tradicao Hipermercados',
        'ShipAddress': 'Av. Ines de Castro, 414',
        'ShipCity': 'Sao Paulo',
        'ShipRegion': 'SP',
        'ShipCountry': 'Brazil',
        'EmployeeID': 3,
        'Verified': false
    },
    {
        'OrderID': 10293,
        'CustomerID': 'ID-TORTU',
        'CustomerName': 'Felipe Izquierdo',
        'OrderDate': new Date(2024, 5, 29),
        'ShippedDate': new Date(2024, 6, 11),
        'Freight': 21.18,
        'ShipName': 'Tortuga Restaurante',
        'ShipAddress': 'Avda. Azteca 123',
        'ShipCity': 'Mexico D.F.',
        'ShipRegion': null,
        'ShipCountry': 'Mexico',
        'EmployeeID': 1,
        'Verified': false
    },
    {
        'OrderID': 10294,
        'CustomerID': 'ID-RATTC',
        'CustomerName': 'Fran Wilson',
        'OrderDate': new Date(2024, 5, 30),
        'ShippedDate': new Date(2024, 6, 5),
        'Freight': 147.26,
        'ShipName': 'Rattlesnake Canyon Grocery',
        'ShipAddress': '2817 Milton Dr.',
        'ShipCity': 'Albuquerque',
        'ShipRegion': 'NM',
        'ShipCountry': 'USA',
        'EmployeeID': 2,
        'Verified': false
    },
    {
        'OrderID': 10295,
        'CustomerID': 'ID-VINET',
        'CustomerName': 'Giovanni Rovelli',
        'OrderDate': new Date(2024, 5, 2),
        'ShippedDate': new Date(2024, 5, 10),
        'Freight': 1.15,
        'ShipName': 'Vins et alcools Chevalier',
        'ShipAddress': '59 rue de l Abbaye',
        'ShipCity': 'Reims',
        'ShipRegion': null,
        'ShipCountry': 'France',
        'EmployeeID': 3,
        'Verified': false
    },
    {
        'OrderID': 10296,
        'CustomerID': 'ID-LILAS',
        'CustomerName': 'Catherine Dewey',
        'OrderDate': new Date(2024, 5, 3),
        'ShippedDate': new Date(2024, 5, 11),
        'Freight': 0.12,
        'ShipName': 'LILA-Supermercado',
        'ShipAddress': 'Carrera 52 con Ave. Bolivar #65-98 Llano Largo',
        'ShipCity': 'Barquisimeto',
        'ShipRegion': 'Lara',
        'ShipCountry': 'Venezuela',
        'EmployeeID': 4,
        'Verified': true
    },
    {
        'OrderID': 10297,
        'CustomerID': 'ID-BLONP',
        'CustomerName': 'Jean Fresniere',
        'OrderDate': new Date(2024, 5, 4),
        'ShippedDate': new Date(2024, 5, 10),
        'Freight': 5.74,
        'ShipName': 'Blondel pere et fils',
        'ShipAddress': '24, place Kleber',
        'ShipCity': 'Strasbourg',
        'ShipRegion': null,
        'ShipCountry': 'France',
        'EmployeeID': 5,
        'Verified': false
    },
    {
        'OrderID': 10298,
        'CustomerID': 'ID-HUNGO',
        'CustomerName': 'Alexander Feuer',
        'OrderDate': new Date(2024, 5, 5),
        'ShippedDate': new Date(2024, 5, 11),
        'Freight': 168.22,
        'ShipName': 'Hungry Owl All-Night Grocers',
        'ShipAddress': '8 Johnstown Road',
        'ShipCity': 'Cork',
        'ShipRegion': 'Co. Cork',
        'ShipCountry': 'Ireland',
        'EmployeeID': 6,
        'Verified': true
    },
    {
        'OrderID': 10299,
        'CustomerID': 'ID-RICAR',
        'CustomerName': 'Simon Crowther',
        'OrderDate': new Date(2024, 5, 6),
        'ShippedDate': new Date(2024, 5, 13),
        'Freight': 29.76,
        'ShipName': 'Ricardo Adocicados',
        'ShipAddress': 'Av. Copacabana, 267',
        'ShipCity': 'Rio de Janeiro',
        'ShipRegion': 'RJ',
        'ShipCountry': 'Brazil',
        'EmployeeID': 7,
        'Verified': false
    },
    {
        'OrderID': 10300,
        'CustomerID': 'ID-MAGAA',
        'CustomerName': 'Yvonne Moncada',
        'OrderDate': new Date(2024, 5, 9),
        'ShippedDate': new Date(2024, 5, 18),
        'Freight': 17.68,
        'ShipName': 'Magazzini Alimentari Riuniti',
        'ShipAddress': 'Via Ludovico il Moro 22',
        'ShipCity': 'Bergamo',
        'ShipRegion': null,
        'ShipCountry': 'Italy',
        'EmployeeID': 8,
        'Verified': false
    },
    {
        'OrderID': 10301,
        'CustomerID': 'ID-WANDK',
        'CustomerName': 'Rene Phillips',
        'OrderDate': new Date(2024, 5, 9),
        'ShippedDate': new Date(2024, 5, 17),
        'Freight': 45.08,
        'ShipName': 'Die Wandernde Kuh',
        'ShipAddress': 'Adenauerallee 900',
        'ShipCity': 'Stuttgart',
        'ShipRegion': null,
        'ShipCountry': 'Germany',
        'EmployeeID': 9,
        'Verified': true
    },
    {
        'OrderID': 10302,
        'CustomerID': 'ID-SUPRD',
        'CustomerName': 'Pirkko Koskitalo',
        'OrderDate': new Date(2024, 5, 10),
        'ShippedDate': new Date(2024, 6, 9),
        'Freight': 6.27,
        'ShipName': 'Supremes delices',
        'ShipAddress': 'Boulevard Tirou, 255',
        'ShipCity': 'Charleroi',
        'ShipRegion': null,
        'ShipCountry': 'Belgium',
        'EmployeeID': 2,
        'Verified': false
    },
    {
        'OrderID': 10303,
        'CustomerID': 'ID-GODOS',
        'CustomerName': 'Paula Parente',
        'OrderDate': new Date(2024, 5, 11),
        'ShippedDate': new Date(2024, 5, 18),
        'Freight': 107.83,
        'ShipName': 'Godos Cocina Tipica',
        'ShipAddress': 'C/ Romero, 33',
        'ShipCity': 'Sevilla',
        'ShipRegion': null,
        'ShipCountry': 'Spain',
        'EmployeeID': 4,
        'Verified': false
    },
    {
        'OrderID': 10304,
        'CustomerID': 'ID-TORTU',
        'CustomerName': 'Karl Jablonski',
        'OrderDate': new Date(2024, 5, 12),
        'ShippedDate': new Date(2024, 5, 17),
        'Freight': 63.79,
        'ShipName': 'Tortuga Restaurante',
        'ShipAddress': 'Avda. Azteca 123',
        'ShipCity': 'Mexico D.F.',
        'ShipRegion': null,
        'ShipCountry': 'Mexico',
        'EmployeeID': 8,
        'Verified': true
    },
    {
        'OrderID': 10305,
        'CustomerID': 'ID-OLDWO',
        'CustomerName': 'Matti Karttunen',
        'OrderDate': new Date(2024, 5, 13),
        'ShippedDate': new Date(2024, 6, 9),
        'Freight': 257.62,
        'ShipName': 'Old World Delicatessen',
        'ShipAddress': '2743 Bering St.',
        'ShipCity': 'Anchorage',
        'ShipRegion': 'AK',
        'ShipCountry': 'USA',
        'EmployeeID': 6,
        'Verified': false
    },
    {
        'OrderID': 10306,
        'CustomerID': 'ID-ROMEY',
        'CustomerName': 'Zbyszek Piestrzeniewicz',
        'OrderDate': new Date(2024, 5, 16),
        'ShippedDate': new Date(2024, 5, 23),
        'Freight': 7.56,
        'ShipName': 'Romero y tomillo',
        'ShipAddress': 'Gran Via, 1',
        'ShipCity': 'Madrid',
        'ShipRegion': null,
        'ShipCountry': 'Spain',
        'EmployeeID': 3,
        'Verified': false
    },
    {
        'OrderID': 10307,
        'CustomerID': 'ID-LONEP',
        'CustomerName': 'Zbyszek Piestrzeniewicz',
        'OrderDate': new Date(2024, 5, 17),
        'ShippedDate': new Date(2024, 5, 25),
        'Freight': 0.56,
        'ShipName': 'Lonesome Pine Restaurant',
        'ShipAddress': '89 Chiaroscuro Rd.',
        'ShipCity': 'Portland',
        'ShipRegion': 'OR',
        'ShipCountry': 'USA',
        'EmployeeID': 1,
        'Verified': true
    }
];