
export interface PizzaItem {
  Id: number;
  Title: string;
  Type: string;
  Size: string;
  Description: string;
  Tags: string[];
  ImageURL: string;
  Price: string;
  OriginalPrice?: string;
}

export const pizzaMenu: PizzaItem[] = [
    {
        "Id": 1,
        "Title": "Mexican Green Wave",
        "Type": "Vegetarian",
        "Size": "Small",
        "Description": "Stromboli sandwich with chili sauce.",
        "Tags": ['Onions', 'Pepper', 'Cheese'],
        "ImageURL": "Mexican_Green_Wave.jpg",
        "Price": "$4.79",
        "OriginalPrice": "$6.58",
    },
    {
        "Id": 2,
        "Title": "Fresh Veggie",
        "Type": "Vegetarian",
        "Size": "Medium",
        "Description": "Veggie with Onions and Capsicum.",
        "Tags": ['Onions', 'Capsicum'],
        "ImageURL": "Fresh_Veggie.jpg",
        "Price": "$11.99",
    },
    {
        "Id": 3,
        "Title": "Peppy Paneer",
        "Type": "Vegetarian",
        "Size": "Large",
        "Description": "It's made using toppings of tomato, mozzarella cheese and fresh basil.",
        "Tags": ['Onions', 'Pepper', 'Cheese'],
        "ImageURL": "Peppy_Paneer.jpg",
        "Price": "$14.99",
        "OriginalPrice": "$16.08",
    },
    {
        "Id": 4,
        "Title": "Margherita",
        "Type": "Vegetarian",
        "Size": "Small",
        "Description": "Lebanese Pizza topped with tomato sauce.",
        "Tags": ['Onions', 'Pepper', 'Cheese'],
        "ImageURL": "Margherit.jpg",
        "Price": "$4.79",
        "OriginalPrice": "$7.56",
    },
    {
        "Id": 5,
        "Title": "Indian Tandoori Paneer",
        "Type": "Vegetarian",
        "Size": "Medium",
        "Description": "Tandoori Paneer with capsicum, red paprika and mint.",
        "Tags": ['Paneer', 'Capsicum'],
        "ImageURL": "IndianTandooriPaneer.jpg",
        "Price": "$11.99",
    },
    {
        "Id": 6,
        "Title": "Pepper Barbecue Chicken",
        "Type": "Non-Vegetarian",
        "Size": "Medium",
        "Description": "Pepper Barbecue Chicken with cheese.",
        "Tags": ['Pepper', 'Chicken', 'Cheese'],
        "ImageURL": "Pepper_Barbeque.jpg",
        "Price": "$11.99",
    },
    {
        "Id": 7,
        "Title": "Chicken Sausage",
        "Type": "Non-Vegetarian",
        "Size": "Large",
        "Description": "Chicken Sausage with cheese.",
        "Tags": ['Cheese', 'Chicken'],
        "ImageURL": "Chicken_Sausage.jpg",
        "Price": "$14.99",
    },
    {
        "Id": 8,
        "Title": "Chicken Golden Delight",
        "Type": "Non-Vegetarian",
        "Size": "Large",
        "Description": "Barbeque chicken with a topping of golden corn loaded with extra cheese.",
        "Tags": ['Onions', 'BBQ', 'Prawn'],
        "ImageURL": "Chicken_Golden_Delight.jpg",
        "Price": "$14.99",
        "OriginalPrice": "$17.99",
    },
    {
        "Id": 9,
        "Title": "Pepper Barbecue and Onion",
        "Type": "Non-Vegetarian",
        "Size": "Medium",
        "Description": "Pepper Barbecue chicken with Onion.",
        "Tags": ['Pepper', 'Chicken'],
        "ImageURL": "Pepper_Barbeque_Onion.jpg",
        "Price": "$11.99",
    },
    {
        "Id": 10,
        "Title": "Chicken Fiesta",
        "Type": "Non-Vegetarian",
        "Size": "Small",
        "Description": "Grilled Chicken Rashers with Peri-Peri chicken, Onion and Capsicum.",
        "Tags": ['Chicken', 'Capsicum'],
        "ImageURL": "chunky-chicken.png",
        "Price": "$4.79",
        "OriginalPrice": "$9.58",
    },
    {
        "Id": 11,
        "Title": "Double Cheese Margherita",
        "Type": "Vegetarian",
        "Size": "Medium",
        "Description": "Margherita with chili sauce and double Cheese.",
        "Tags": ['Onions', 'Pepper'],
        "ImageURL": "Double_Cheese_Margherita.jpg",
        "Price": "$11.99",
    },
    {
        "Id": 12,
        "Title": "Veggie Paradise",
        "Type": "Vegetarian",
        "Size": "Large",
        "Description": "Veggie Delight with Goldern Corn, Black Olives, Capsicum and red Paprika.",
        "Tags": ['Corn', 'Capsicum'],
        "ImageURL": "Veggie_Paradise.jpg",
        "Price": "$14.99",
        "OriginalPrice": "$15.62",
    },
    {
        "Id": 13,
        "Title": "Cheese and Corn",
        "Type": "Vegetarian",
        "Size": "Large",
        "Description": "Cheese with golden corn.",
        "Tags": ['Cheese', 'Corn'],
        "ImageURL": "Corn_Cheese.jpg",
        "Price": "$14.99",
    },
    {
        "Id": 14,
        "Title": "Chicken Tikka",
        "Type": "Non-Vegetarian",
        "Size": "Medium",
        "Description": "Tandoori masala with Chicken Tikka, Onion, red paprika and mint.",
        "Tags": ['Chicken', 'Tikka', 'Paprika'],
        "ImageURL": "IndianChickenTikka.jpg",
        "Price": "$11.99",
        "OriginalPrice": "$12.02",
    },
    {
        "Id": 15,
        "Title": "Chicken Dominator",
        "Type": "Non-Vegetarian",
        "Size": "Small",
        "Description": "Double Pepper Barbecue Chicken with Peri-Peri Chicken, Chicken Tikka, Grilled and Rashers.",
        "Tags": ['Pepper', 'Chicken'],
        "ImageURL": "Dominator.jpg",
        "Price": "$4.79",
        "OriginalPrice": "$6.30",
    },
    {
        "Id": 16,
        "Title": "Deluxe Veggie",
        "Type": "Vegetarian",
        "Size": "Medium",
        "Description": "Onions and Capsicum those delectable mushrooms with paneer and golden corn to top it all.",
        "Tags": ['Mushrooms', 'Corn'],
        "ImageURL": "Deluxe_Veggie.jpg",
        "Price": "$11.99",
    },
    {
        "Id": 17,
        "Title": "Farm House",
        "Type": "Vegetarian",
        "Size": "Large",
        "Description": "Crunchy, crisp capsicum, succulent mushrooms and fresh tomatoes.",
        "Tags": ['Capsicum', 'Mushrooms'],
        "ImageURL": "Farmhouse.jpg",
        "Price": "$14.99",
    },
    {
        "Id": 18,
        "Title": "Veg Extravanganza",
        "Type": "Vegetarian",
        "Size": "Large",
        "Description": "Pizza with corn, olives, onions, capsicum, tomatoes and jalapeno with cheese to go all around.",
        "Tags": ['Corn', 'Mushrooms'],
        "ImageURL": "Veg_Extravaganz.jpg",
        "Price": "$14.99",
        "OriginalPrice": "$19.58",
    },
    {
        "Id": 19,
        "Title": "Margherita",
        "Type": "Vegetarian",
        "Size": "Small",
        "Description": "Lebanese Pizza topped with tomato sauce.",
        "Tags": ['Onions', 'Pepper', 'Cheese'],
        "ImageURL": "Margherit.jpg",
        "Price": "$4.79",
        "OriginalPrice": "$7.77",
    },
    {
        "Id": 20,
        "Title": "Pepper Barbecue and Onion",
        "Type": "Non-Vegetarian",
        "Size": "Medium",
        "Description": "Pepper Barbecue chicken with Onion.",
        "Tags": ['Onions', 'Pepper', 'Chicken'],
        "ImageURL": "Pepper_Barbeque_Onion.jpg",
        "Price": "$11.99",
    },
    {
        "Id": 21,
        "Title": "Veggie Paradise",
        "Type": "Vegetarian",
        "Size": "Large",
        "Description": "Veggie Delight with Goldern Corn, Black Olives, Capsicum and red Paprika.",
        "Tags": ['Corn', 'Capsicum', 'Pepper'],
        "ImageURL": "Veggie_Paradise.jpg",
        "Price": "$14.99",
        "OriginalPrice": "$15.34",
    },
    {
        "Id": 22,
        "Title": "Chicken Dominator",
        "Type": "Non-Vegetarian",
        "Size": "Small",
        "Description": "Double Pepper Barbecue Chicken with Peri-Peri Chicken, Chicken Tikka, Grilled and Rashers.",
        "Tags": ['Pepper', 'Chicken'],
        "ImageURL": "Dominator.jpg",
        "Price": "$4.79",
    }
];