export const productSalesDetails: object[] =[
  {
    "SaleID": "S-001",
    "ProductName": "Laptop",
    "UnitsSold": 15,
    "UnitPrice": 346.63,
    "TotalRevenue": 5199.45,
    "IsDiscounted": false,
    "Category": "Electronics",
    "Region": "Central",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-002",
    "ProductName": "Phone",
    "UnitsSold": 5,
    "UnitPrice": 858.85,
    "TotalRevenue": 4294.25,
    "IsDiscounted": false,
    "Category": "Office Equipment",
    "Region": "South",
    "SalesPerson": "George"
  },
  {
    "SaleID": "S-003",
    "ProductName": "Tablet",
    "UnitsSold": 12,
    "UnitPrice": 607.82,
    "TotalRevenue": 7293.84,
    "IsDiscounted": false,
    "Category": "Home Tech",
    "Region": "South",
    "SalesPerson": "George"
  },
  {
    "SaleID": "S-004",
    "ProductName": "Headphones",
    "UnitsSold": 16,
    "UnitPrice": 748.68,
    "TotalRevenue": 11978.88,
    "IsDiscounted": false,
    "Category": "Office Equipment",
    "Region": "West",
    "SalesPerson": "Charlie"
  },
  {
    "SaleID": "S-005",
    "ProductName": "Monitor",
    "UnitsSold": 1,
    "UnitPrice": 545.7,
    "TotalRevenue": 545.7,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "East",
    "SalesPerson": "Alice"
  },
  {
    "SaleID": "S-006",
    "ProductName": "Keyboard",
    "UnitsSold": 6,
    "UnitPrice": 611.56,
    "TotalRevenue": 3669.36,
    "IsDiscounted": false,
    "Category": "Office Equipment",
    "Region": "South",
    "SalesPerson": "George"
  },
  {
    "SaleID": "S-007",
    "ProductName": "Mouse",
    "UnitsSold": 14,
    "UnitPrice": 101.15,
    "TotalRevenue": 1416.1,
    "IsDiscounted": false,
    "Category": "Accessories",
    "Region": "South",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-008",
    "ProductName": "Speaker",
    "UnitsSold": 10,
    "UnitPrice": 95.45,
    "TotalRevenue": 954.5,
    "IsDiscounted": true,
    "Category": "Home Tech",
    "Region": "South",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-009",
    "ProductName": "Desktop",
    "UnitsSold": 18,
    "UnitPrice": 344.4,
    "TotalRevenue": 6199.2,
    "IsDiscounted": true,
    "Category": "Electronics",
    "Region": "North",
    "SalesPerson": "Diana"
  },
  {
    "SaleID": "S-010",
    "ProductName": "Camera",
    "UnitsSold": 8,
    "UnitPrice": 691.63,
    "TotalRevenue": 5533.04,
    "IsDiscounted": false,
    "Category": "Office Equipment",
    "Region": "East",
    "SalesPerson": "Alice"
  },
  {
    "SaleID": "S-011",
    "ProductName": "Printer",
    "UnitsSold": 7,
    "UnitPrice": 795.2,
    "TotalRevenue": 5566.4,
    "IsDiscounted": false,
    "Category": "Accessories",
    "Region": "East",
    "SalesPerson": "Julia"
  },
  {
    "SaleID": "S-012",
    "ProductName": "Smartwatch",
    "UnitsSold": 17,
    "UnitPrice": 452.39,
    "TotalRevenue": 7690.63,
    "IsDiscounted": false,
    "Category": "Electronics",
    "Region": "South",
    "SalesPerson": "Diana"
  },
  {
    "SaleID": "S-013",
    "ProductName": "TV",
    "UnitsSold": 3,
    "UnitPrice": 482.38,
    "TotalRevenue": 1447.14,
    "IsDiscounted": false,
    "Category": "Home Tech",
    "Region": "North",
    "SalesPerson": "Ian"
  },
  {
    "SaleID": "S-014",
    "ProductName": "Router",
    "UnitsSold": 14,
    "UnitPrice": 798.8,
    "TotalRevenue": 11183.2,
    "IsDiscounted": false,
    "Category": "Office Equipment",
    "Region": "Central",
    "SalesPerson": "Hannah"
  },
  {
    "SaleID": "S-015",
    "ProductName": "Charger",
    "UnitsSold": 19,
    "UnitPrice": 191.56,
    "TotalRevenue": 3639.64,
    "IsDiscounted": true,
    "Category": "Wearables",
    "Region": "North",
    "SalesPerson": "Ian"
  },
  {
    "SaleID": "S-016",
    "ProductName": "Headset",
    "UnitsSold": 4,
    "UnitPrice": 261.87,
    "TotalRevenue": 1047.48,
    "IsDiscounted": false,
    "Category": "Wearables",
    "Region": "Central",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-017",
    "ProductName": "Projector",
    "UnitsSold": 13,
    "UnitPrice": 283.02,
    "TotalRevenue": 3679.26,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "North",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-018",
    "ProductName": "Hard Drive",
    "UnitsSold": 19,
    "UnitPrice": 818.02,
    "TotalRevenue": 15542.38,
    "IsDiscounted": false,
    "Category": "Accessories",
    "Region": "East",
    "SalesPerson": "Ian"
  },
  {
    "SaleID": "S-019",
    "ProductName": "Webcam",
    "UnitsSold": 5,
    "UnitPrice": 537.02,
    "TotalRevenue": 2685.1,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "South",
    "SalesPerson": "Ian"
  },
  {
    "SaleID": "S-020",
    "ProductName": "Microphone",
    "UnitsSold": 18,
    "UnitPrice": 440.79,
    "TotalRevenue": 7934.22,
    "IsDiscounted": false,
    "Category": "Home Tech",
    "Region": "North",
    "SalesPerson": "Hannah"
  },
  {
    "SaleID": "S-021",
    "ProductName": "Gaming Console",
    "UnitsSold": 13,
    "UnitPrice": 436.01,
    "TotalRevenue": 5668.13,
    "IsDiscounted": true,
    "Category": "Wearables",
    "Region": "South",
    "SalesPerson": "Charlie"
  },
  {
    "SaleID": "S-022",
    "ProductName": "USB Drive",
    "UnitsSold": 19,
    "UnitPrice": 859.65,
    "TotalRevenue": 16333.35,
    "IsDiscounted": false,
    "Category": "Electronics",
    "Region": "South",
    "SalesPerson": "Julia"
  },
  {
    "SaleID": "S-023",
    "ProductName": "LED Light",
    "UnitsSold": 7,
    "UnitPrice": 300.49,
    "TotalRevenue": 2103.43,
    "IsDiscounted": true,
    "Category": "Electronics",
    "Region": "North",
    "SalesPerson": "Fiona"
  },
  {
    "SaleID": "S-024",
    "ProductName": "Power Bank",
    "UnitsSold": 8,
    "UnitPrice": 450.26,
    "TotalRevenue": 3602.08,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "South",
    "SalesPerson": "Hannah"
  },
  {
    "SaleID": "S-025",
    "ProductName": "Bluetooth Speaker",
    "UnitsSold": 7,
    "UnitPrice": 415.83,
    "TotalRevenue": 2910.81,
    "IsDiscounted": true,
    "Category": "Electronics",
    "Region": "South",
    "SalesPerson": "Ethan"
  },
  {
    "SaleID": "S-026",
    "ProductName": "External SSD",
    "UnitsSold": 2,
    "UnitPrice": 331.53,
    "TotalRevenue": 663.06,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "South",
    "SalesPerson": "Charlie"
  },
  {
    "SaleID": "S-027",
    "ProductName": "Smart TV",
    "UnitsSold": 1,
    "UnitPrice": 649.17,
    "TotalRevenue": 649.17,
    "IsDiscounted": true,
    "Category": "Wearables",
    "Region": "North",
    "SalesPerson": "Charlie"
  },
  {
    "SaleID": "S-028",
    "ProductName": "Laptop Bag",
    "UnitsSold": 2,
    "UnitPrice": 877.92,
    "TotalRevenue": 1755.84,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "Central",
    "SalesPerson": "Ethan"
  },
  {
    "SaleID": "S-029",
    "ProductName": "Mouse Pad",
    "UnitsSold": 2,
    "UnitPrice": 351.96,
    "TotalRevenue": 703.92,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "South",
    "SalesPerson": "Diana"
  },
  {
    "SaleID": "S-030",
    "ProductName": "Docking Station",
    "UnitsSold": 11,
    "UnitPrice": 644.8,
    "TotalRevenue": 7092.8,
    "IsDiscounted": true,
    "Category": "Wearables",
    "Region": "West",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-031",
    "ProductName": "Graphics Card",
    "UnitsSold": 6,
    "UnitPrice": 303.77,
    "TotalRevenue": 1822.62,
    "IsDiscounted": false,
    "Category": "Wearables",
    "Region": "West",
    "SalesPerson": "Diana"
  },
  {
    "SaleID": "S-032",
    "ProductName": "VR Headset",
    "UnitsSold": 8,
    "UnitPrice": 980.0,
    "TotalRevenue": 7840.0,
    "IsDiscounted": false,
    "Category": "Wearables",
    "Region": "North",
    "SalesPerson": "Fiona"
  },
  {
    "SaleID": "S-033",
    "ProductName": "Smart Glasses",
    "UnitsSold": 18,
    "UnitPrice": 384.14,
    "TotalRevenue": 6914.52,
    "IsDiscounted": false,
    "Category": "Wearables",
    "Region": "South",
    "SalesPerson": "Charlie"
  },
  {
    "SaleID": "S-034",
    "ProductName": "Fitness Tracker",
    "UnitsSold": 8,
    "UnitPrice": 371.29,
    "TotalRevenue": 2970.32,
    "IsDiscounted": false,
    "Category": "Electronics",
    "Region": "East",
    "SalesPerson": "Hannah"
  },
  {
    "SaleID": "S-035",
    "ProductName": "Smart Plug",
    "UnitsSold": 6,
    "UnitPrice": 946.73,
    "TotalRevenue": 5680.38,
    "IsDiscounted": false,
    "Category": "Wearables",
    "Region": "Central",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-036",
    "ProductName": "Smart Bulb",
    "UnitsSold": 13,
    "UnitPrice": 861.86,
    "TotalRevenue": 11204.18,
    "IsDiscounted": false,
    "Category": "Office Equipment",
    "Region": "West",
    "SalesPerson": "George"
  },
  {
    "SaleID": "S-037",
    "ProductName": "E-Reader",
    "UnitsSold": 16,
    "UnitPrice": 832.72,
    "TotalRevenue": 13323.52,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "East",
    "SalesPerson": "Ian"
  },
  {
    "SaleID": "S-038",
    "ProductName": "Drone",
    "UnitsSold": 5,
    "UnitPrice": 520.94,
    "TotalRevenue": 2604.7,
    "IsDiscounted": false,
    "Category": "Accessories",
    "Region": "East",
    "SalesPerson": "Hannah"
  },
  {
    "SaleID": "S-039",
    "ProductName": "Action Camera",
    "UnitsSold": 2,
    "UnitPrice": 203.8,
    "TotalRevenue": 407.6,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "West",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-040",
    "ProductName": "NAS Device",
    "UnitsSold": 19,
    "UnitPrice": 483.12,
    "TotalRevenue": 9179.28,
    "IsDiscounted": false,
    "Category": "Home Tech",
    "Region": "West",
    "SalesPerson": "Julia"
  },
  {
    "SaleID": "S-041",
    "ProductName": "Streaming Stick",
    "UnitsSold": 11,
    "UnitPrice": 234.93,
    "TotalRevenue": 2584.23,
    "IsDiscounted": true,
    "Category": "Electronics",
    "Region": "West",
    "SalesPerson": "Ian"
  },
  {
    "SaleID": "S-042",
    "ProductName": "Smart Lock",
    "UnitsSold": 20,
    "UnitPrice": 143.38,
    "TotalRevenue": 2867.6,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "Central",
    "SalesPerson": "Fiona"
  },
  {
    "SaleID": "S-043",
    "ProductName": "Thermostat",
    "UnitsSold": 13,
    "UnitPrice": 975.97,
    "TotalRevenue": 12687.61,
    "IsDiscounted": false,
    "Category": "Wearables",
    "Region": "East",
    "SalesPerson": "Fiona"
  },
  {
    "SaleID": "S-044",
    "ProductName": "Security Camera",
    "UnitsSold": 18,
    "UnitPrice": 573.1,
    "TotalRevenue": 10315.8,
    "IsDiscounted": true,
    "Category": "Office Equipment",
    "Region": "East",
    "SalesPerson": "Diana"
  },
  {
    "SaleID": "S-045",
    "ProductName": "Wireless Charger",
    "UnitsSold": 16,
    "UnitPrice": 651.72,
    "TotalRevenue": 10427.52,
    "IsDiscounted": true,
    "Category": "Accessories",
    "Region": "North",
    "SalesPerson": "Julia"
  },
  {
    "SaleID": "S-046",
    "ProductName": "Memory Card",
    "UnitsSold": 15,
    "UnitPrice": 300.41,
    "TotalRevenue": 4506.15,
    "IsDiscounted": false,
    "Category": "Home Tech",
    "Region": "North",
    "SalesPerson": "Alice"
  },
  {
    "SaleID": "S-047",
    "ProductName": "Stylus Pen",
    "UnitsSold": 10,
    "UnitPrice": 601.68,
    "TotalRevenue": 6016.8,
    "IsDiscounted": true,
    "Category": "Office Equipment",
    "Region": "Central",
    "SalesPerson": "Bob"
  },
  {
    "SaleID": "S-048",
    "ProductName": "Monitor Stand",
    "UnitsSold": 4,
    "UnitPrice": 848.79,
    "TotalRevenue": 3395.16,
    "IsDiscounted": false,
    "Category": "Wearables",
    "Region": "Central",
    "SalesPerson": "Alice"
  },
  {
    "SaleID": "S-049",
    "ProductName": "Cable Organizer",
    "UnitsSold": 8,
    "UnitPrice": 362.61,
    "TotalRevenue": 2900.88,
    "IsDiscounted": true,
    "Category": "Home Tech",
    "Region": "South",
    "SalesPerson": "Hannah"
  },
  {
    "SaleID": "S-050",
    "ProductName": "Laptop",
    "UnitsSold": 13,
    "UnitPrice": 389.95,
    "TotalRevenue": 5069.35,
    "IsDiscounted": true,
    "Category": "Home Tech",
    "Region": "West",
    "SalesPerson": "Hannah"
  }
]