export interface MenuItem {
  ItemID: string;
  ItemName: string;
  Price: number;
  Category: string;
  SpiceLevel: string;
  IsAvailable: boolean;
  IsSeasonal: boolean;
  Description: string;
  CuisineType: string;
  RecommendedPairing: string;
  OrderFrequency: number;
}

export const restaurantMenu: MenuItem[] = [
    {
        "ItemID": "ITEM-1001",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 9.0,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": false,
        "SpiceLevel": "Hot",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 30
    },
    {
        "ItemID": "ITEM-1002",
        "ItemName": "Fruit Salad",
        "Category": "Salad",
        "Price": 16.61,
        "Description": "Fruit Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 64
    },
    {
        "ItemID": "ITEM-1003",
        "ItemName": "Tiramisu",
        "Category": "Dessert",
        "Price": 11.24,
        "Description": "Tiramisu - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 91
    },
    {
        "ItemID": "ITEM-1004",
        "ItemName": "Chocolate Cake",
        "Category": "Dessert",
        "Price": 14.46,
        "Description": "Chocolate Cake - a delightful dessert option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 56
    },
    {
        "ItemID": "ITEM-1005",
        "ItemName": "Stuffed Mushrooms",
        "Category": "Appetizer",
        "Price": 5.07,
        "Description": "Stuffed Mushrooms - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 70
    },
    {
        "ItemID": "ITEM-1006",
        "ItemName": "Coleslaw",
        "Category": "Salad",
        "Price": 13.26,
        "Description": "Coleslaw - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 12
    },
    {
        "ItemID": "ITEM-1007",
        "ItemName": "Greek Salad",
        "Category": "Salad",
        "Price": 10.42,
        "Description": "Greek Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 74
    },
    {
        "ItemID": "ITEM-1008",
        "ItemName": "Nachos",
        "Category": "Appetizer",
        "Price": 10.06,
        "Description": "Nachos - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Hot",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 17
    },
    {
        "ItemID": "ITEM-1009",
        "ItemName": "Iced Tea",
        "Category": "Beverage",
        "Price": 7.37,
        "Description": "Iced Tea - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 35
    },
    {
        "ItemID": "ITEM-1010",
        "ItemName": "Garlic Bread",
        "Category": "Appetizer",
        "Price": 14.34,
        "Description": "Garlic Bread - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 22
    },
    {
        "ItemID": "ITEM-1011",
        "ItemName": "Spring Rolls",
        "Category": "Appetizer",
        "Price": 6.87,
        "Description": "Spring Rolls - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 53
    },
    {
        "ItemID": "ITEM-1012",
        "ItemName": "Spaghetti Bolognese",
        "Category": "Main Course",
        "Price": 17.15,
        "Description": "Spaghetti Bolognese - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 63
    },
    {
        "ItemID": "ITEM-1013",
        "ItemName": "Paneer Tikka Masala",
        "Category": "Main Course",
        "Price": 18.08,
        "Description": "Paneer Tikka Masala - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Hot",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 78
    },
    {
        "ItemID": "ITEM-1014",
        "ItemName": "Chocolate Cake",
        "Category": "Dessert",
        "Price": 20.0,
        "Description": "Chocolate Cake - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 67
    },
    {
        "ItemID": "ITEM-1015",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 18.22,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": false,
        "SpiceLevel": "Medium",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 69
    },
    {
        "ItemID": "ITEM-1016",
        "ItemName": "Mango Smoothie",
        "Category": "Beverage",
        "Price": 24.44,
        "Description": "Mango Smoothie - a delightful beverage option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 59
    },
    {
        "ItemID": "ITEM-1017",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 5.26,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 84
    },
    {
        "ItemID": "ITEM-1018",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 22.28,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 31
    },
    {
        "ItemID": "ITEM-1019",
        "ItemName": "Cappuccino",
        "Category": "Beverage",
        "Price": 8.79,
        "Description": "Cappuccino - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 100
    },
    {
        "ItemID": "ITEM-1020",
        "ItemName": "Garlic Bread",
        "Category": "Appetizer",
        "Price": 18.14,
        "Description": "Garlic Bread - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 83
    },
    {
        "ItemID": "ITEM-1021",
        "ItemName": "Bruschetta",
        "Category": "Appetizer",
        "Price": 20.41,
        "Description": "Bruschetta - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 59
    },
    {
        "ItemID": "ITEM-1022",
        "ItemName": "Caesar Salad",
        "Category": "Salad",
        "Price": 22.95,
        "Description": "Caesar Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 72
    },
    {
        "ItemID": "ITEM-1023",
        "ItemName": "Cappuccino",
        "Category": "Beverage",
        "Price": 19.57,
        "Description": "Cappuccino - a delightful beverage option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 37
    },
    {
        "ItemID": "ITEM-1024",
        "ItemName": "Nachos",
        "Category": "Appetizer",
        "Price": 20.01,
        "Description": "Nachos - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Medium",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 42
    },
    {
        "ItemID": "ITEM-1025",
        "ItemName": "Chocolate Cake",
        "Category": "Dessert",
        "Price": 14.54,
        "Description": "Chocolate Cake - a delightful dessert option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 87
    },
    {
        "ItemID": "ITEM-1026",
        "ItemName": "Nachos",
        "Category": "Appetizer",
        "Price": 7.63,
        "Description": "Nachos - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Medium",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 92
    },
    {
        "ItemID": "ITEM-1027",
        "ItemName": "Greek Salad",
        "Category": "Salad",
        "Price": 23.72,
        "Description": "Greek Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 42
    },
    {
        "ItemID": "ITEM-1028",
        "ItemName": "Fruit Salad",
        "Category": "Salad",
        "Price": 8.4,
        "Description": "Fruit Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 39
    },
    {
        "ItemID": "ITEM-1029",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 17.12,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 21
    },
    {
        "ItemID": "ITEM-1030",
        "ItemName": "Margherita Pizza",
        "Category": "Main Course",
        "Price": 11.26,
        "Description": "Margherita Pizza - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 42
    },
    {
        "ItemID": "ITEM-1031",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 18.09,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 43
    },
    {
        "ItemID": "ITEM-1032",
        "ItemName": "Cheesecake",
        "Category": "Dessert",
        "Price": 5.47,
        "Description": "Cheesecake - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 23
    },
    {
        "ItemID": "ITEM-1033",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 10.31,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 99
    },
    {
        "ItemID": "ITEM-1034",
        "ItemName": "Cappuccino",
        "Category": "Beverage",
        "Price": 19.22,
        "Description": "Cappuccino - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 89
    },
    {
        "ItemID": "ITEM-1035",
        "ItemName": "Beef Burger",
        "Category": "Main Course",
        "Price": 23.81,
        "Description": "Beef Burger - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Medium",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 20
    },
    {
        "ItemID": "ITEM-1036",
        "ItemName": "Mango Smoothie",
        "Category": "Beverage",
        "Price": 22.88,
        "Description": "Mango Smoothie - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 31
    },
    {
        "ItemID": "ITEM-1037",
        "ItemName": "Iced Tea",
        "Category": "Beverage",
        "Price": 6.16,
        "Description": "Iced Tea - a delightful beverage option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 94
    },
    {
        "ItemID": "ITEM-1038",
        "ItemName": "Ice Cream Sundae",
        "Category": "Dessert",
        "Price": 15.33,
        "Description": "Ice Cream Sundae - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 87
    },
    {
        "ItemID": "ITEM-1039",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 7.46,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 91
    },
    {
        "ItemID": "ITEM-1040",
        "ItemName": "Stuffed Mushrooms",
        "Category": "Appetizer",
        "Price": 11.36,
        "Description": "Stuffed Mushrooms - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 37
    },
    {
        "ItemID": "ITEM-1041",
        "ItemName": "Spring Rolls",
        "Category": "Appetizer",
        "Price": 24.04,
        "Description": "Spring Rolls - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Medium",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 29
    },
    {
        "ItemID": "ITEM-1042",
        "ItemName": "Spring Rolls",
        "Category": "Appetizer",
        "Price": 19.0,
        "Description": "Spring Rolls - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Medium",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 17
    },
    {
        "ItemID": "ITEM-1043",
        "ItemName": "Iced Tea",
        "Category": "Beverage",
        "Price": 15.33,
        "Description": "Iced Tea - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 11
    },
    {
        "ItemID": "ITEM-1044",
        "ItemName": "Gulab Jamun",
        "Category": "Dessert",
        "Price": 16.19,
        "Description": "Gulab Jamun - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 86
    },
    {
        "ItemID": "ITEM-1045",
        "ItemName": "Fruit Salad",
        "Category": "Salad",
        "Price": 20.5,
        "Description": "Fruit Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 51
    },
    {
        "ItemID": "ITEM-1046",
        "ItemName": "Coleslaw",
        "Category": "Salad",
        "Price": 14.65,
        "Description": "Coleslaw - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 50
    },
    {
        "ItemID": "ITEM-1047",
        "ItemName": "Cheesecake",
        "Category": "Dessert",
        "Price": 16.15,
        "Description": "Cheesecake - a delightful dessert option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 28
    },
    {
        "ItemID": "ITEM-1048",
        "ItemName": "Cheesecake",
        "Category": "Dessert",
        "Price": 7.67,
        "Description": "Cheesecake - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 32
    },
    {
        "ItemID": "ITEM-1049",
        "ItemName": "Margherita Pizza",
        "Category": "Main Course",
        "Price": 18.76,
        "Description": "Margherita Pizza - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 68
    },
    {
        "ItemID": "ITEM-1050",
        "ItemName": "Stuffed Mushrooms",
        "Category": "Appetizer",
        "Price": 21.0,
        "Description": "Stuffed Mushrooms - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 66
    }
];

export const foodOrderData: object[] = [
    {
        "ItemID": "ITEM-1001",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 9,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": false,
        "SpiceLevel": "Hot",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 30
    },
    {
        "ItemID": "ITEM-1002",
        "ItemName": "Fruit Salad",
        "Category": "Salad",
        "Price": 16,
        "Description": "Fruit Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 64
    },
    {
        "ItemID": "ITEM-1003",
        "ItemName": "Tiramisu",
        "Category": "Dessert",
        "Price": 11,
        "Description": "Tiramisu - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 91
    },
    {
        "ItemID": "ITEM-1004",
        "ItemName": "Chocolate Cake",
        "Category": "Dessert",
        "Price": 14,
        "Description": "Chocolate Cake - a delightful dessert option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 56
    },
    {
        "ItemID": "ITEM-1005",
        "ItemName": "Stuffed Mushrooms",
        "Category": "Appetizer",
        "Price": 5,
        "Description": "Stuffed Mushrooms - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 70
    },
    {
        "ItemID": "ITEM-1006",
        "ItemName": "Coleslaw",
        "Category": "Salad",
        "Price": 13,
        "Description": "Coleslaw - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 12
    },
    {
        "ItemID": "ITEM-1007",
        "ItemName": "Greek Salad",
        "Category": "Salad",
        "Price": 10,
        "Description": "Greek Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 74
    },
    {
        "ItemID": "ITEM-1008",
        "ItemName": "Nachos",
        "Category": "Appetizer",
        "Price": 10,
        "Description": "Nachos - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Hot",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 17
    },
    {
        "ItemID": "ITEM-1009",
        "ItemName": "Iced Tea",
        "Category": "Beverage",
        "Price": 7,
        "Description": "Iced Tea - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 35
    },
    {
        "ItemID": "ITEM-1010",
        "ItemName": "Garlic Bread",
        "Category": "Appetizer",
        "Price": 14,
        "Description": "Garlic Bread - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 22
    },
    {
        "ItemID": "ITEM-1011",
        "ItemName": "Spring Rolls",
        "Category": "Appetizer",
        "Price": 6,
        "Description": "Spring Rolls - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 53
    },
    {
        "ItemID": "ITEM-1012",
        "ItemName": "Spaghetti Bolognese",
        "Category": "Main Course",
        "Price": 17,
        "Description": "Spaghetti Bolognese - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 63
    },
    {
        "ItemID": "ITEM-1013",
        "ItemName": "Paneer Tikka Masala",
        "Category": "Main Course",
        "Price": 18,
        "Description": "Paneer Tikka Masala - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Hot",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 78
    },
    {
        "ItemID": "ITEM-1014",
        "ItemName": "Chocolate Cake",
        "Category": "Dessert",
        "Price": 20,
        "Description": "Chocolate Cake - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 67
    },
    {
        "ItemID": "ITEM-1015",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 18,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": false,
        "SpiceLevel": "Hot",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 69
    },
    {
        "ItemID": "ITEM-1016",
        "ItemName": "Mango Smoothie",
        "Category": "Beverage",
        "Price": 24,
        "Description": "Mango Smoothie - a delightful beverage option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 59
    },
    {
        "ItemID": "ITEM-1017",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 5,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 84
    },
    {
        "ItemID": "ITEM-1018",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 22,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Hot",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 31
    },
    {
        "ItemID": "ITEM-1019",
        "ItemName": "Cappuccino",
        "Category": "Beverage",
        "Price": 8,
        "Description": "Cappuccino - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 100
    },
    {
        "ItemID": "ITEM-1020",
        "ItemName": "Garlic Bread",
        "Category": "Appetizer",
        "Price": 18,
        "Description": "Garlic Bread - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 83
    },
    {
        "ItemID": "ITEM-1021",
        "ItemName": "Bruschetta",
        "Category": "Appetizer",
        "Price": 20,
        "Description": "Bruschetta - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 59
    },
    {
        "ItemID": "ITEM-1022",
        "ItemName": "Caesar Salad",
        "Category": "Salad",
        "Price": 22,
        "Description": "Caesar Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 72
    },
    {
        "ItemID": "ITEM-1023",
        "ItemName": "Cappuccino",
        "Category": "Beverage",
        "Price": 20,
        "Description": "Cappuccino - a delightful beverage option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 37
    },
    {
        "ItemID": "ITEM-1024",
        "ItemName": "Nachos",
        "Category": "Appetizer",
        "Price": 20,
        "Description": "Nachos - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Hot",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 42
    },
    {
        "ItemID": "ITEM-1025",
        "ItemName": "Chocolate Cake",
        "Category": "Dessert",
        "Price": 14,
        "Description": "Chocolate Cake - a delightful dessert option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 87
    },
    {
        "ItemID": "ITEM-1026",
        "ItemName": "Nachos",
        "Category": "Appetizer",
        "Price": 7,
        "Description": "Nachos - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Hot",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 92
    },
    {
        "ItemID": "ITEM-1027",
        "ItemName": "Greek Salad",
        "Category": "Salad",
        "Price": 23,
        "Description": "Greek Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 42
    },
    {
        "ItemID": "ITEM-1028",
        "ItemName": "Fruit Salad",
        "Category": "Salad",
        "Price": 8,
        "Description": "Fruit Salad - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 39
    },
    {
        "ItemID": "ITEM-1029",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 17,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 21
    },
    {
        "ItemID": "ITEM-1030",
        "ItemName": "Margherita Pizza",
        "Category": "Main Course",
        "Price": 11,
        "Description": "Margherita Pizza - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": true,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 42
    },
    {
        "ItemID": "ITEM-1031",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 18,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 43
    },
    {
        "ItemID": "ITEM-1032",
        "ItemName": "Cheesecake",
        "Category": "Dessert",
        "Price": 5,
        "Description": "Cheesecake - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 23
    },
    {
        "ItemID": "ITEM-1033",
        "ItemName": "Grilled Chicken",
        "Category": "Main Course",
        "Price": 10,
        "Description": "Grilled Chicken - a delightful main course option.",
        "IsAvailable": false,
        "SpiceLevel": "Hot",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 99
    },
    {
        "ItemID": "ITEM-1034",
        "ItemName": "Cappuccino",
        "Category": "Beverage",
        "Price": 19,
        "Description": "Cappuccino - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 89
    },
    {
        "ItemID": "ITEM-1035",
        "ItemName": "Beef Burger",
        "Category": "Main Course",
        "Price": 23,
        "Description": "Beef Burger - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 20
    },
    {
        "ItemID": "ITEM-1036",
        "ItemName": "Mango Smoothie",
        "Category": "Beverage",
        "Price": 22,
        "Description": "Mango Smoothie - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 31
    },
    {
        "ItemID": "ITEM-1037",
        "ItemName": "Iced Tea",
        "Category": "Beverage",
        "Price": 6,
        "Description": "Iced Tea - a delightful beverage option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 94
    },
    {
        "ItemID": "ITEM-1038",
        "ItemName": "Ice Cream Sundae",
        "Category": "Dessert",
        "Price": 15,
        "Description": "Ice Cream Sundae - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 87
    },
    {
        "ItemID": "ITEM-1039",
        "ItemName": "Quinoa Salad",
        "Category": "Salad",
        "Price": 7,
        "Description": "Quinoa Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": false,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 91
    },
    {
        "ItemID": "ITEM-1040",
        "ItemName": "Stuffed Mushrooms",
        "Category": "Appetizer",
        "Price": 11,
        "Description": "Stuffed Mushrooms - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "Green Salad",
        "OrderFrequency": 37
    },
    {
        "ItemID": "ITEM-1041",
        "ItemName": "Spring Rolls",
        "Category": "Appetizer",
        "Price": 24,
        "Description": "Spring Rolls - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "American",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 29
    },
    {
        "ItemID": "ITEM-1042",
        "ItemName": "Spring Rolls",
        "Category": "Appetizer",
        "Price": 19,
        "Description": "Spring Rolls - a delightful appetizer option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Chinese",
        "IsSeasonal": false,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 17
    },
    {
        "ItemID": "ITEM-1043",
        "ItemName": "Iced Tea",
        "Category": "Beverage",
        "Price": 15,
        "Description": "Iced Tea - a delightful beverage option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "Italian",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 11
    },
    {
        "ItemID": "ITEM-1044",
        "ItemName": "Gulab Jamun",
        "Category": "Dessert",
        "Price": 16,
        "Description": "Gulab Jamun - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 86
    },
    {
        "ItemID": "ITEM-1045",
        "ItemName": "Fruit Salad",
        "Category": "Salad",
        "Price": 20,
        "Description": "Fruit Salad - a delightful salad option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 51
    },
    {
        "ItemID": "ITEM-1046",
        "ItemName": "Coleslaw",
        "Category": "Salad",
        "Price": 14,
        "Description": "Coleslaw - a delightful salad option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 50
    },
    {
        "ItemID": "ITEM-1047",
        "ItemName": "Cheesecake",
        "Category": "Dessert",
        "Price": 16,
        "Description": "Cheesecake - a delightful dessert option.",
        "IsAvailable": false,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Red Wine",
        "OrderFrequency": 28
    },
    {
        "ItemID": "ITEM-1048",
        "ItemName": "Cheesecake",
        "Category": "Dessert",
        "Price": 7,
        "Description": "Cheesecake - a delightful dessert option.",
        "IsAvailable": true,
        "SpiceLevel": "None",
        "CuisineType": "American",
        "IsSeasonal": true,
        "RecommendedPairing": "Garlic Bread",
        "OrderFrequency": 32
    },
    {
        "ItemID": "ITEM-1049",
        "ItemName": "Margherita Pizza",
        "Category": "Main Course",
        "Price": 18,
        "Description": "Margherita Pizza - a delightful main course option.",
        "IsAvailable": true,
        "SpiceLevel": "Mild",
        "CuisineType": "Mexican",
        "IsSeasonal": false,
        "RecommendedPairing": "Iced Tea",
        "OrderFrequency": 68
    },
    {
        "ItemID": "ITEM-1050",
        "ItemName": "Stuffed Mushrooms",
        "Category": "Appetizer",
        "Price": 21,
        "Description": "Stuffed Mushrooms - a delightful appetizer option.",
        "IsAvailable": false,
        "SpiceLevel": "Mild",
        "CuisineType": "Chinese",
        "IsSeasonal": true,
        "RecommendedPairing": "French Fries",
        "OrderFrequency": 66
    }
];